// Minna no Nihongo I, Bab 3–25. Pattern rows: [title, tag, formula, desc, jp, romaji, arti]
module.exports = [
  {
    bab: 3, file: "28", title: "Tempat & Lokasi", titleJp: "ここ・そこ・あそこ",
    hook: "Toiletnya di mana, ya? Yuk belajar menunjuk tempat pakai ここ・そこ・あそこ.",
    cta: "Coba tanya lokasi tempat di sekitarmu pakai doko desu ka!",
    patterns: [
      ["Koko / Soko / Asoko", "di sini · di situ · di sana", "t:ここ / t:そこ / t:あそこ",
        "Penunjuk TEMPAT: ここ = di sini (dekat aku), そこ = di situ (dekat kamu), あそこ = di sana (jauh dari kita). Versi sopannya: こちら / そちら / あちら.",
        "トイレはあそこです。", "toire wa asoko desu", "Toiletnya di sana."],
      ["KB wa [tempat] desu", "X ada di ...", "KB + p:は + n:tempat + d:です",
        "Pola untuk memberi tahu posisi benda, tempat, atau orang: \"X ada di [tempat].\"",
        "アンディさんはじむしょです。", "Andi-san wa jimusho desu", "Andi ada di kantor."],
      ["Doko / Dochira", "di mana?", "t:どこ / t:どちら",
        "どこ = \"di mana?\". どちら lebih sopan, juga dipakai untuk menanyakan negara, perusahaan, atau sekolah seseorang.",
        "エレベーターはどこですか。", "erebeetaa wa doko desu ka", "Liftnya di mana?"],
      ["KB no KB", "buatan / asal", "KB1 + p:の + KB2",
        "の di sini menunjukkan ASAL atau BUATAN. にほんの くるま = mobil buatan Jepang. Untuk bertanya: どこの ～ですか.",
        "これはにほんのくるまです。", "kore wa Nihon no kuruma desu", "Ini mobil buatan Jepang."],
      ["Keluarga Ko-So-A-Do", "hafal satu, dapat semua", "t:こ / t:そ / t:あ / t:ど",
        "こ = dekat aku, そ = dekat kamu, あ = jauh, ど = pertanyaan. Berlaku untuk benda (これ), tempat (ここ), dan arah/sopan (こちら).",
        "ここはどこですか。", "koko wa doko desu ka", "Di sini di mana?"],
      ["O~ (awalan sopan)", "lebih halus", "o:お + KB",
        "お di depan kata benda biar lebih sopan. Contoh: くに → おくに, なまえ → おなまえ.",
        "おくにはどちらですか。", "okuni wa dochira desu ka", "Anda dari negara mana?"],
    ],
    summary: [["Koko/soko/asoko", "ここ・そこ・あそこ"], ["X ada di ...", "は～です"], ["Di mana?", "どこ・どちら"],
      ["Buatan / asal", "の"], ["Ko-so-a-do", "こ・そ・あ・ど"], ["Awalan sopan", "お〜"]],
  },
  {
    bab: 4, file: "29", title: "Waktu & Kata Kerja", titleJp: "いま なんじですか",
    hook: "Sekarang jam berapa? Yuk belajar menyebut jam dan cerita kegiatan harianmu.",
    cta: "Coba ceritakan jadwal harianmu dari pagi sampai malam!",
    patterns: [
      ["~ji ~fun", "menyebut jam", "n:angka o:じ n:angka o:ふん／ぷん",
        "Sebut jam: angka + じ (jam) + angka + ふん/ぷん (menit). Untuk bertanya jam: いま なんじですか.",
        "いま7じ10ぷんです。", "ima shichi-ji juppun desu", "Sekarang pukul 7 lewat 10 menit."],
      ["Bentuk ~masu", "kata kerja sopan", "d:ます / d:ません / d:ました / d:ませんでした",
        "Cukup ganti ekornya! ます = sekarang/akan, ません = tidak, ました = sudah (lampau), ませんでした = tidak (lampau).",
        "きのうべんきょうしました。", "kinou benkyou shimashita", "Kemarin (sudah) belajar."],
      ["Waktu + ni", "pada jam / hari", "n:waktu + p:に + KK",
        "Waktu yang spesifik (jam, tanggal, hari) ditempeli に. Tapi きょう, あした, まいにち TIDAK pakai に, ya!",
        "6じにおきます。", "rokuji ni okimasu", "Bangun pukul 6."],
      ["Kara ~ Made", "dari ~ sampai", "KB1 + p:から + KB2 + p:まで",
        "から = dari, まで = sampai. Untuk batas waktu atau tempat. Boleh juga dipakai sendiri-sendiri.",
        "9じから5じまではたらきます。", "kuji kara goji made hatarakimasu", "Bekerja dari pukul 9 sampai 5."],
      ["KB to KB", "dan", "KB1 + p:と + KB2",
        "と = \"dan\", untuk menyambung dua KATA BENDA saja (bukan kalimat).",
        "やすみはどようびとにちようびです。", "yasumi wa doyoubi to nichiyoubi desu", "Liburnya hari Sabtu dan Minggu."],
      ["~ne", "...ya / ...kan", "d:です + p:ね",
        "ね di akhir kalimat untuk minta persetujuan atau mempertegas, mirip \"...ya\" atau \"...kan?\".",
        "たいへんですね。", "taihen desu ne", "Wah, berat ya."],
    ],
    summary: [["Menyebut jam", "～じ～ふん"], ["Bentuk -masu", "ます・ました"], ["Waktu + ni", "に"],
      ["Dari ~ sampai", "から・まで"], ["Dan (KB)", "と"], ["...ya / ...kan", "ね"]],
  },
  {
    bab: 5, file: "30", title: "Pergi & Datang", titleJp: "いきます・きます・かえります",
    hook: "Mau ke mana, naik apa, sama siapa? Semuanya bisa dijawab di bab ini!",
    cta: "Coba ceritakan kamu pergi ke mana, naik apa, dan sama siapa!",
    patterns: [
      ["e ikimasu", "pergi ke ...", "n:tempat + p:へ + v:いきます",
        "へ (dibaca \"e\"!) menunjukkan arah tujuan. いきます = pergi, きます = datang, かえります = pulang.",
        "バンドンへいきます。", "Bandon e ikimasu", "Pergi ke Bandung."],
      ["Doko e mo ~masen", "tidak ke mana-mana", "t:どこ + p:へ + p:も + v:いきません",
        "Kata tanya + も + kata kerja NEGATIF = \"sama sekali tidak\". どこへも いきません = tidak ke mana-mana.",
        "どこへもいきません。", "doko e mo ikimasen", "Tidak pergi ke mana-mana."],
      ["Kendaraan + de", "naik ...", "n:kendaraan + p:で + v:いきます",
        "で menunjukkan cara/alat. Naik kendaraan pakai で. Tapi jalan kaki cukup あるいて (tanpa で).",
        "でんしゃでいきます。", "densha de ikimasu", "Pergi naik kereta."],
      ["Orang + to", "bersama ...", "n:orang + p:と + KK",
        "と di sini artinya \"bersama\". Kalau sendirian, pakai ひとりで (tanpa と).",
        "かぞくとにほんへきました。", "kazoku to Nihon e kimashita", "Datang ke Jepang bersama keluarga."],
      ["Itsu", "kapan?", "t:いつ",
        "いつ = \"kapan?\". Beda dengan keterangan waktu lain, いつ TIDAK pakai に.",
        "いつにほんへきましたか。", "itsu Nihon e kimashita ka", "Kapan datang ke Jepang?"],
      ["~yo", "...lho", "d:です + p:よ",
        "よ di akhir kalimat untuk memberi info baru yang mungkin belum diketahui lawan bicara, mirip \"...lho\".",
        "このでんしゃはボゴールへいきますよ。", "kono densha wa Bogooru e ikimasu yo", "Kereta ini ke Bogor, lho."],
      ["Sou desu ne", "iya, betul", "d:そうですね",
        "Untuk setuju atau sependapat: \"iya, ya\" / \"betul juga\". Beda dengan そうですか yang untuk info baru.",
        "そうですね。", "sou desu ne", "Iya, betul."],
    ],
    summary: [["Pergi ke", "へ いきます"], ["Tidak ke mana-mana", "どこへも"], ["Naik kendaraan", "で"],
      ["Bersama orang", "と"], ["Kapan?", "いつ"], ["...lho", "よ"], ["Iya, betul", "そうですね"]],
  },
  {
    bab: 6, file: "31", title: "Aktivitas Sehari-hari", titleJp: "を・で",
    hook: "Makan apa, minum apa, ngapain? Yuk kenalan sama partikel を dan cara mengajak teman.",
    cta: "Coba ajak temanmu pakai ~masen ka!",
    patterns: [
      ["KB o KK", "penanda objek", "KB + p:を + KK",
        "を menandai OBJEK — benda yang dikenai aksi. Minum APA? ジュースを のみます.",
        "ジュースをのみます。", "juusu o nomimasu", "Minum jus."],
      ["KB o shimasu", "melakukan", "KB + p:を + v:します",
        "します = melakukan. Tempelkan ke kegiatan: olahraga, permainan, atau acara. サッカーを します = main bola.",
        "テニスをします。", "tenisu o shimasu", "Bermain tenis."],
      ["Nani o shimasu ka", "ngapain?", "t:なに + p:を + v:します + p:か",
        "Untuk bertanya \"melakukan apa?\": なに (apa) + を + しますか.",
        "にちようびなにをしますか。", "nichiyoubi nani o shimasu ka", "Hari Minggu ngapain?"],
      ["Nan / Nani", "dua cara baca 何", "t:なん / t:なに",
        "Huruf 何 punya dua bacaan. なん sebelum です atau bunyi d/t/n (なんですか). なに di luar itu (なにを).",
        "それはなんですか。", "sore wa nan desu ka", "Itu apa?"],
      ["Tempat + de", "tempat kegiatan", "n:tempat + p:で + KK",
        "で menunjukkan TEMPAT kegiatan dilakukan. (Beda dengan で kendaraan di Bab 5, ya!)",
        "えきでしんぶんをかいます。", "eki de shinbun o kaimasu", "Beli koran di stasiun."],
      ["~masen ka", "ajakan sopan", "KK + d:ませんか",
        "Untuk mengajak dengan sopan: \"maukah...?\" / \"bagaimana kalau...?\"",
        "いっしょにバンドンへいきませんか。", "issho ni Bandon e ikimasen ka", "Mau pergi ke Bandung bareng?"],
      ["~mashou", "ayo!", "KK + d:ましょう",
        "\"Ayo / mari kita...\". Untuk mengajak, atau untuk menerima ajakan orang lain.",
        "いっしょにひるごはんをたべましょう。", "issho ni hirugohan o tabemashou", "Ayo makan siang bareng."],
      ["~ka (oh, ...ya?)", "paham info baru", "d:です + p:か",
        "か juga dipakai saat menerima info baru lalu paham, mirip \"oh, begitu ya?\". Nadanya turun.",
        "バンドンですか。いいですね。", "Bandon desu ka. ii desu ne", "Oh, ke Bandung ya? Asyik."],
    ],
    summary: [["Objek", "を"], ["Melakukan", "を します"], ["Ngapain?", "なにを"], ["Nan / nani", "なん・なに"],
      ["Tempat kegiatan", "で"], ["Ajakan sopan", "ませんか"], ["Ayo!", "ましょう"], ["Oh, ...ya?", "か"]],
  },
  {
    bab: 7, file: "32", title: "Memberi & Menerima", titleJp: "あげます・もらいます",
    hook: "Dapat hadiah dari siapa? Yuk belajar memberi dan menerima dalam bahasa Jepang.",
    cta: "Coba ceritakan hadiah yang pernah kamu beri dan terima!",
    patterns: [
      ["Alat + de", "pakai ...", "n:alat + p:で + KK",
        "で menunjukkan ALAT atau CARA. はしで たべます = makan pakai sumpit. \"Dalam bahasa ~\" juga pakai で: にほんごで.",
        "はしでたべます。", "hashi de tabemasu", "Makan pakai sumpit."],
      ["~go de nan desu ka", "bahasa ~-nya apa?", "g:「X」 + p:は + n:～ご + p:で + t:なん + d:ですか",
        "Untuk bertanya \"X dalam bahasa Y apa?\". Pas banget kalau kita lupa satu kata.",
        "「ありがとう」はえいごでなんですか。", "\"arigatou\" wa eigo de nan desu ka", "\"Arigatou\" dalam bahasa Inggris apa?"],
      ["Agemasu", "memberi", "n:orang + p:に + KB + p:を + v:あげます",
        "あげます = memberi. に menandai si PENERIMA. Pola yang sama untuk かします (meminjamkan) dan おしえます (mengajari).",
        "シティさんにはなをあげます。", "Siti-san ni hana o agemasu", "Memberi bunga kepada Siti."],
      ["Moraimasu", "menerima", "n:orang + p:に + KB + p:を + v:もらいます",
        "もらいます = menerima. に menandai si PEMBERI (boleh diganti から). Dari lembaga/perusahaan WAJIB pakai から.",
        "デウィさんにはなをもらいました。", "Dewi-san ni hana o moraimashita", "Menerima bunga dari Dewi."],
      ["Mou ~mashita", "sudah", "o:もう + KK + d:ました",
        "もう = \"sudah\", untuk sesuatu yang sudah selesai. Kalau belum, jawab まだです (belum).",
        "もうにもつをおくりましたか。", "mou nimotsu o okurimashita ka", "Barangnya sudah dikirim?"],
      ["Tanpa partikel", "gaya santai", "p:は / p:が / p:を → g:✕",
        "Dalam obrolan santai, partikel kadang DIHILANGKAN kalau maknanya sudah jelas: このスプーン[は] すてきですね.",
        "このスプーン、すてきですね。", "kono supuun, suteki desu ne", "Sendok ini bagus ya."],
    ],
    summary: [["Pakai alat", "で"], ["Bahasa ~-nya?", "～ごで"], ["Memberi", "あげます"],
      ["Menerima", "もらいます"], ["Sudah", "もう"], ["Tanpa partikel", "は・を ✕"]],
  },
  {
    bab: 8, file: "33", title: "Kata Sifat", titleJp: "おおきい・きれいな",
    hook: "Cantik, tinggi, enak, mahal — yuk belajar menggambarkan benda pakai kata sifat.",
    cta: "Coba gambarkan kotamu pakai kata sifat!",
    patterns: [
      ["KS-i & KS-na", "dua jenis kata sifat", "a:KSい / a:KSな",
        "Ada 2 jenis kata sifat: KS-い (おおきい, たかい) dan KS-な (きれい, しずか). Cara berubahnya beda, jadi kenali dulu!",
        "さくらはきれいです。", "sakura wa kirei desu", "Bunga sakura cantik."],
      ["KB wa KS desu", "sifat (positif)", "KB + p:は + KS + d:です",
        "\"X itu [sifat]\". KS-な langsung + です (tanpa な). KS-い: ～い + です.",
        "ブロモさんはたかいです。", "Buromo-san wa takai desu", "Gunung Bromo tinggi."],
      ["KS negatif", "tidak ...", "a:KSな d:じゃ_ありません / a:KSくない d:です",
        "KS-な → じゃ ありません. KS-い → buang い, ganti ～くないです. Spesial: いい → よくないです.",
        "このほんはおもしろくないです。", "kono hon wa omoshirokunai desu", "Buku ini tidak menarik."],
      ["KS + KB", "sifat di depan benda", "a:KSな + KB / a:KSい + KB",
        "KS-な pakai な sebelum benda (しずかな へや). KS-い langsung menempel (たかい やま).",
        "しずかなへやです。", "shizuka na heya desu", "Kamar yang tenang."],
      ["~ga, ~", "tetapi", "g:～です + p:が g:、～",
        "が di tengah kalimat = \"tetapi\", untuk menyambung dua hal yang berlawanan.",
        "にほんのたべものはおいしいですが、たかいです。", "Nihon no tabemono wa oishii desu ga, takai desu", "Makanan Jepang enak, tapi mahal."],
      ["Totemo / Amari", "sangat / kurang", "o:とても / o:あまり",
        "とても = sangat (kalimat positif). あまり = kurang/tidak begitu, WAJIB dengan bentuk negatif.",
        "ディエンはとてもさむいです。", "Dien wa totemo samui desu", "Dieng sangat dingin."],
      ["Dou desu ka", "gimana?", "KB + p:は + t:どう + d:ですか",
        "Untuk menanyakan kesan atau pendapat: \"gimana ...?\"",
        "にほんのせいかつはどうですか。", "Nihon no seikatsu wa dou desu ka", "Bagaimana kehidupan di Jepang?"],
      ["Donna + KB", "yang seperti apa?", "t:どんな + KB",
        "どんな untuk menanyakan sifat/jenis: \"... yang seperti apa?\". Selalu diikuti kata benda.",
        "ジョグジャカルタはどんなまちですか。", "Jogjakarta wa donna machi desu ka", "Yogyakarta kota yang seperti apa?"],
    ],
    summary: [["Dua jenis KS", "い・な"], ["Sifat positif", "～です"], ["Sifat negatif", "～くない"],
      ["KS + benda", "な／い"], ["Tetapi", "が"], ["Sangat / kurang", "とても・あまり"], ["Gimana?", "どう"], ["Seperti apa?", "どんな"]],
  },
  {
    bab: 9, file: "34", title: "Suka, Bisa & Alasan", titleJp: "すき・わかります・から",
    hook: "Suka apa? Bisa apa? Kenapa? Yuk belajar ngomongin kesukaan dan alasan.",
    cta: "Coba sebutkan hal yang kamu suka dan alasannya!",
    patterns: [
      ["KB ga suki desu", "suka / mengerti", "KB + p:が + a:すき + d:です",
        "Untuk hal yang disukai, dikuasai, atau dimengerti, objeknya pakai が (bukan を): すき, きらい, じょうず, へた, わかります, あります.",
        "わたしはにほんごがわかります。", "watashi wa nihongo ga wakarimasu", "Saya mengerti bahasa Jepang."],
      ["Donna KB ga suki?", "suka apa?", "t:どんな + KB + p:が + a:すき + d:ですか",
        "Untuk menanyakan kesukaan secara terbuka: \"suka ... apa?\"",
        "どんなスポーツがすきですか。", "donna supootsu ga suki desu ka", "Suka olahraga apa?"],
      ["Yoku / Amari / Zenzen", "seberapa", "o:よく / o:すこし / o:あまり / o:ぜんぜん",
        "Ditaruh sebelum kata kerja: よく (sering/baik), すこし (sedikit). あまり (kurang) & ぜんぜん (sama sekali) WAJIB dengan negatif.",
        "えいごがあまりわかりません。", "eigo ga amari wakarimasen", "Kurang mengerti bahasa Inggris."],
      ["~kara", "karena", "g:～ + p:から g:、～",
        "から di akhir anak kalimat = \"karena\", untuk memberi alasan.",
        "じかんがありませんから、しんぶんをよみません。", "jikan ga arimasen kara, shinbun o yomimasen", "Karena tidak ada waktu, saya tidak baca koran."],
      ["Doushite", "kenapa?", "t:どうして g:～か → g:～ p:から",
        "どうして = \"kenapa?\". Jawabannya pakai ～から (karena).",
        "どうしてはやくかえりますか。", "doushite hayaku kaerimasu ka", "Kenapa pulang cepat?"],
    ],
    summary: [["Suka / mengerti", "が"], ["Suka apa?", "どんな"], ["Seberapa", "よく・あまり"],
      ["Karena", "から"], ["Kenapa?", "どうして"]],
  },
  {
    bab: 10, file: "35", title: "Ada & Posisi", titleJp: "あります・います",
    hook: "Ada kucing di bawah meja? Yuk belajar bilang \"ada\" dan posisi benda.",
    cta: "Coba sebutkan benda apa saja yang ada di kamarmu!",
    patterns: [
      ["Arimasu / Imasu", "ada", "KB + p:が + v:あります / KB + p:が + v:います",
        "あります untuk benda mati & tumbuhan. います untuk makhluk hidup yang bisa bergerak (orang, hewan).",
        "にわにいぬがいます。", "niwa ni inu ga imasu", "Ada anjing di halaman."],
      ["[Tempat] ni KB ga arimasu", "di ... ada ...", "n:tempat + p:に + KB + p:が + v:あります",
        "に menunjukkan LOKASI keberadaan: [tempat] に [benda] が あります/います.",
        "へやにつくえがあります。", "heya ni tsukue ga arimasu", "Di kamar ada meja."],
      ["KB wa [tempat] ni arimasu", "X ada di mana", "KB + p:は + n:tempat + p:に + v:あります",
        "Kalau bendanya sudah jadi TOPIK (sudah dikenal), pakai pola ini untuk bilang X ada di mana.",
        "トイレはあそこにあります。", "toire wa asoko ni arimasu", "Toiletnya ada di sana."],
      ["KB no [posisi]", "atas, bawah, dalam...", "KB + p:の + n:posisi",
        "Kata posisi (うえ atas, した bawah, なか dalam, となり sebelah, まえ depan, うしろ belakang) disambung dengan の.",
        "つくえのうえにほんがあります。", "tsukue no ue ni hon ga arimasu", "Di atas meja ada buku."],
      ["KB ya KB (nado)", "dan lain-lain", "KB1 + p:や + KB2 + p:など",
        "や = \"dan (antara lain)\", untuk menyebut beberapa contoh saja. Bisa ditutup など. Beda dengan と yang menyebut SEMUA.",
        "はこのなかにてがみやしゃしんがあります。", "hako no naka ni tegami ya shashin ga arimasu", "Di dalam kotak ada surat, foto, dll."],
    ],
    summary: [["Ada", "あります・います"], ["Di ... ada ...", "に～が"], ["X ada di ...", "は～に"],
      ["Posisi", "うえ・した"], ["Dan lain-lain", "や・など"]],
  },
  {
    bab: 11, file: "36", title: "Menghitung Jumlah", titleJp: "ひとつ・ふたつ・みっつ",
    hook: "Satu, dua, tiga… tapi kok cara menghitungnya beda-beda? Yuk kenalan sama counter!",
    cta: "Coba hitung benda-benda di mejamu dalam bahasa Jepang!",
    patterns: [
      ["Kata bantu bilangan", "counter", "o:～つ / o:～にん / o:～だい / o:～まい",
        "ひとつ～とお untuk benda umum. ～にん orang (ひとり, ふたり), ～だい mesin/kendaraan, ～まい benda tipis, ～かい kali.",
        "りんごをよっつかいます。", "ringo o yottsu kaimasu", "Membeli empat apel."],
      ["Letak jumlah", "sebelum kata kerja", "KB + p:を／が + n:jumlah + KK",
        "Angka + counter ditaruh SETELAH partikel, tepat sebelum kata kerja. Tidak perlu の.",
        "がくせいがふたりいます。", "gakusei ga futari imasu", "Ada dua mahasiswa."],
      ["Ikutsu / Nan~", "berapa?", "t:いくつ / t:なん～ / t:どのくらい",
        "いくつ = berapa buah, なん + counter (なんにん = berapa orang), どのくらい = berapa lama.",
        "みかんをいくつかいましたか。", "mikan o ikutsu kaimashita ka", "Beli berapa jeruk?"],
      ["~ni ~kai", "seberapa sering", "n:jangka + p:に + o:～かい + KK",
        "Untuk frekuensi: [jangka waktu] に [angka] かい. Contoh: sebulan dua kali.",
        "1かげつに2かいえいがをみます。", "ikkagetsu ni nikai eiga o mimasu", "Nonton film dua kali sebulan."],
      ["~dake", "hanya", "KB + p:だけ",
        "だけ = \"hanya / saja\", ditaruh setelah kata benda atau jumlah.",
        "やすみはにちようびだけです。", "yasumi wa nichiyoubi dake desu", "Liburnya hari Minggu saja."],
    ],
    summary: [["Counter", "～つ・～にん"], ["Letak jumlah", "を＋jumlah"], ["Berapa?", "いくつ"],
      ["Seberapa sering", "～かい"], ["Hanya", "だけ"]],
  },
  {
    bab: 12, file: "37", title: "Lampau & Perbandingan", titleJp: "より・いちばん",
    hook: "Kemarin gimana? Mana yang lebih enak? Yuk belajar bentuk lampau dan membandingkan.",
    cta: "Coba bandingkan dua makanan favoritmu!",
    patterns: [
      ["Deshita", "lampau KB & KS-na", "d:でした / d:じゃ_ありませんでした",
        "Lampau kalimat kata benda & KS-な: です → でした, じゃ ありません → じゃ ありませんでした.",
        "きのうはあめでした。", "kinou wa ame deshita", "Kemarin hujan."],
      ["~katta desu", "lampau KS-i", "a:～かった d:です / a:～くなかった d:です",
        "KS-い lampau: buang い → ～かったです (positif), ～くなかったです (negatif). Spesial: いい → よかったです.",
        "りょこうはたのしかったです。", "ryokou wa tanoshikatta desu", "Tamasyanya menyenangkan."],
      ["~yori", "lebih ... daripada", "KB1 + p:は + KB2 + p:より + KS + d:です",
        "より = \"daripada\". X は Y より [sifat] です = X lebih [sifat] daripada Y.",
        "このくるまはあのくるまよりおおきいです。", "kono kuruma wa ano kuruma yori ookii desu", "Mobil ini lebih besar daripada mobil itu."],
      ["Dochira ga ~", "mana yang lebih?", "KB1 + p:と + KB2 + p:と + t:どちら + p:が + KS",
        "Untuk memilih dari DUA hal. Jawabnya: [pilihan] の ほうが [sifat] です.",
        "サッカーとやきゅうとどちらがおもしろいですか。", "sakkaa to yakyuu to dochira ga omoshiroi desu ka", "Mana yang lebih seru, sepak bola atau baseball?"],
      ["Ichiban", "paling", "KB + p:で + t:なに + p:が + o:いちばん + KS",
        "いちばん = \"paling\". Pakai kata tanya yang sesuai: なに (benda), どこ (tempat), だれ (orang), いつ (waktu).",
        "にほんりょうりでなにがいちばんおいしいですか。", "Nihon ryouri de nani ga ichiban oishii desu ka", "Masakan Jepang apa yang paling enak?"],
      ["KS-i + no", "yang ...", "a:KSい + p:の",
        "の bisa menggantikan kata benda yang sudah jelas. あかいの = \"yang merah\".",
        "カリナさんのかばんはあのあかいのです。", "Karina-san no kaban wa ano akai no desu", "Tas Karina yang merah itu."],
    ],
    summary: [["Lampau KB", "でした"], ["Lampau KS-i", "～かった"], ["Lebih daripada", "より"],
      ["Mana yang lebih?", "どちら"], ["Paling", "いちばん"], ["Yang ...", "～の"]],
  },
  {
    bab: 13, file: "38", title: "Keinginan", titleJp: "ほしい・～たい",
    hook: "Mau punya apa? Mau ngapain? Yuk belajar ngomongin keinginan.",
    cta: "Coba sebutkan tiga hal yang ingin kamu lakukan tahun ini!",
    patterns: [
      ["~ga hoshii desu", "ingin punya", "KB + p:が + a:ほしい + d:です",
        "ほしい = ingin (punya) sesuatu. Bendanya pakai が. Negatifnya: ほしくないです.",
        "わたしはくるまがほしいです。", "watashi wa kuruma ga hoshii desu", "Saya ingin punya mobil."],
      ["~tai desu", "ingin melakukan", "KK + d:たいです",
        "Ambil bentuk ます, buang ます, tambah たいです: のみます → のみたいです. Negatif: ～たくないです. Hanya untuk keinginan sendiri.",
        "わたしはおきなわへいきたいです。", "watashi wa Okinawa e ikitai desu", "Saya ingin pergi ke Okinawa."],
      ["~ni ikimasu", "pergi untuk ...", "n:tempat + p:へ + KK + p:に + v:いきます",
        "Menyatakan TUJUAN pergi: kata kerja (buang ます) + に + いきます/きます. Kegiatan (KB) langsung + に.",
        "マランへえいがをみにいきます。", "Maran e eiga o mi ni ikimasu", "Pergi ke Malang untuk nonton film."],
      ["Dokoka / Nanika", "suatu tempat / sesuatu", "t:どこか / t:なにか",
        "どこか = (ke) suatu tempat, なにか = sesuatu. Partikel へ atau を sering dihilangkan.",
        "なつやすみはどこかいきましたか。", "natsuyasumi wa dokoka ikimashita ka", "Liburan musim panas pergi ke suatu tempat?"],
      ["Go~ (awalan sopan)", "lebih halus", "o:ご + KB",
        "Mirip お～, ご juga awalan sopan, biasanya untuk kata serapan Cina: ちゅうもん → ごちゅうもん.",
        "ごちゅうもんは？", "gochuumon wa?", "Mau pesan apa?"],
    ],
    summary: [["Ingin punya", "ほしい"], ["Ingin melakukan", "～たい"], ["Pergi untuk ...", "～に いきます"],
      ["Suatu tempat", "どこか・なにか"], ["Awalan sopan", "ご〜"]],
  },
  {
    bab: 14, file: "39", title: "Bentuk -te", titleJp: "～て ください・～て います",
    hook: "Bentuk -te itu kunci ajaib! Yuk belajar minta tolong dan bilang \"sedang\".",
    cta: "Coba minta tolong temanmu pakai ~te kudasai!",
    patterns: [
      ["Kelompok kata kerja", "I · II · III", "v:Kelompok_I / v:Kelompok_II / v:Kelompok_III",
        "Kelompok III: きます & します. Kelompok II: kebanyakan ～えます (たべます) + beberapa ～います (みます). Sisanya Kelompok I.",
        "かきます(I)・たべます(II)・します(III)", "kakimasu (I) · tabemasu (II) · shimasu (III)", "menulis · makan · melakukan"],
      ["Membuat bentuk -te", "aturan ajaib", "v:KKます → v:KKて",
        "I: い/ち/り → って, み/び/に → んで, き → いて, ぎ → いで, し → して (いきます → いって). II: ます → て. III: きて, して.",
        "かきます → かいて", "kakimasu → kaite", "menulis (bentuk -te)"],
      ["~te kudasai", "tolong ...", "v:KKて + d:ください",
        "Untuk minta tolong dengan sopan: bentuk て + ください.",
        "なまえをかいてください。", "namae o kaite kudasai", "Tolong tulis nama."],
      ["~te imasu", "sedang ...", "v:KKて + d:います",
        "Untuk kegiatan yang SEDANG berlangsung: bentuk て + います.",
        "アンディさんはいまでんわをかけています。", "Andi-san wa ima denwa o kakete imasu", "Andi sedang menelepon."],
      ["~mashou ka", "mau saya bantu?", "KK + d:ましょうか",
        "Untuk menawarkan bantuan: \"mau saya ...kan?\"",
        "にもつをもちましょうか。", "nimotsu o mochimashou ka", "Mau saya bawakan barangnya?"],
      ["KB ga KK", "kejadian alam", "KB + p:が + KK",
        "Untuk kejadian alam yang kita lihat atau rasakan (hujan turun, dll), subjeknya pakai が.",
        "あめがふっています。", "ame ga futte imasu", "Sedang hujan."],
      ["Sumimasen ga, ~", "permisi, ...", "d:すみません + p:が g:、～",
        "Pembuka permintaan yang sopan. が di sini hanya kata pembuka, BUKAN \"tetapi\".",
        "すみませんが、しおをとってください。", "sumimasen ga, shio o totte kudasai", "Maaf, tolong ambilkan garam."],
    ],
    summary: [["Kelompok KK", "I・II・III"], ["Bentuk -te", "～て"], ["Tolong ...", "～てください"],
      ["Sedang ...", "～ています"], ["Tawarkan bantuan", "ましょうか"], ["Kejadian alam", "が"], ["Permisi, ...", "すみませんが"]],
  },
  {
    bab: 15, file: "40", title: "Izin & Larangan", titleJp: "～ても いい・～ては いけません",
    hook: "Boleh foto di sini? Yuk belajar minta izin dan memahami larangan.",
    cta: "Coba sebutkan aturan di sekolah atau kantormu!",
    patterns: [
      ["~te mo ii desu ka", "boleh ...?", "v:KKて + p:も + a:いい + d:ですか",
        "Untuk minta izin: \"boleh ...?\". Kalau boleh, jawab: ええ、どうぞ / はい、いいです.",
        "しゃしんをとってもいいですか。", "shashin o totte mo ii desu ka", "Boleh foto?"],
      ["~te wa ikemasen", "tidak boleh", "v:KKて + p:は + v:いけません",
        "Larangan: \"tidak boleh ...\". Nadanya tegas, biasanya untuk aturan.",
        "ここでたばこをすってはいけません。", "koko de tabako o sutte wa ikemasen", "Di sini tidak boleh merokok."],
      ["~te imasu", "keadaan / kebiasaan", "v:KKて + d:います",
        "Selain \"sedang\", ています juga untuk keadaan yang masih berlaku (tinggal, sudah menikah, tahu) dan pekerjaan/kebiasaan.",
        "わたしはスラバヤにすんでいます。", "watashi wa Surabaya ni sunde imasu", "Saya tinggal di Surabaya."],
      ["KB ni KK", "masuk / naik / tiba", "KB + p:に + v:のります",
        "はいります (masuk), のります (naik), dan つきます (tiba) memakai に untuk tujuannya.",
        "でんしゃにのります。", "densha ni norimasu", "Naik kereta."],
      ["[Tempat] ni KB o KK", "tempat hasil aksi", "n:tempat + p:に + KB + p:を + KK",
        "に juga menunjukkan tempat hasil aksi berada, misalnya menulis sesuatu DI sini.",
        "ここにじゅうしょをかいてください。", "koko ni juusho o kaite kudasai", "Tolong tulis alamat di sini."],
    ],
    summary: [["Boleh?", "てもいい"], ["Tidak boleh", "てはいけません"], ["Keadaan", "ています"],
      ["Masuk / naik", "に"], ["Tempat hasil aksi", "に～を"]],
  },
  {
    bab: 16, file: "41", title: "Menyambung Kalimat", titleJp: "～て、～て・～てから",
    hook: "Bangun, mandi, lalu berangkat — yuk belajar menyambung beberapa kegiatan.",
    cta: "Coba ceritakan rutinitas pagimu pakai bentuk -te!",
    patterns: [
      ["~te, ~te, ~", "urutan kegiatan", "v:KKて g:、 v:KKて g:、 KK",
        "Ubah kata kerja sebelum yang terakhir ke bentuk て. KS-い → ～くて, KS-な/KB → で. Waktu ditentukan kata kerja TERAKHIR.",
        "ジョギングをして、シャワーをあびて、かいしゃへいきます。", "jogingu o shite, shawaa o abite, kaisha e ikimasu", "Jogging, mandi, lalu pergi ke kantor."],
      ["~te kara", "setelah ... baru", "v:KKて + p:から + KK",
        "てから = \"setelah ... baru ...\". Menegaskan urutan: yang pertama selesai dulu.",
        "ばんごはんをたべてから、べんきょうします。", "bangohan o tabete kara, benkyou shimasu", "Setelah makan malam, baru belajar."],
      ["KB wa KB ga KS", "X-nya ...", "KB1 + p:は + KB2 + p:が + KS",
        "Untuk sifat BAGIAN dari sesuatu. Topik besar pakai は, bagiannya pakai が.",
        "スラバヤはたべものがおいしいです。", "Surabaya wa tabemono ga oishii desu", "Surabaya makanannya enak."],
      ["[Tempat] o demasu", "keluar / turun dari", "n:tempat + p:を + v:でます",
        "を juga menandai titik AWAL untuk でます (keluar) dan おります (turun).",
        "7じにうちをでます。", "shichi-ji ni uchi o demasu", "Keluar rumah pukul 7."],
      ["Douyatte", "bagaimana caranya?", "t:どうやって",
        "Untuk menanyakan cara atau rute: \"bagaimana caranya pergi ke ...?\"",
        "だいがくまでどうやっていきますか。", "daigaku made douyatte ikimasu ka", "Bagaimana caranya pergi ke kampus?"],
      ["Dore / Dono", "yang mana (3+)", "t:どれ / t:どの + KB",
        "どれ = \"yang mana\" (dari 3 pilihan atau lebih), berdiri sendiri. どの harus diikuti kata benda.",
        "ブディさんのかさはどれですか。", "Budi-san no kasa wa dore desu ka", "Payung Budi yang mana?"],
    ],
    summary: [["Urutan kegiatan", "～て、～て"], ["Setelah ... baru", "～てから"], ["X-nya ...", "は～が"],
      ["Keluar dari", "を でます"], ["Caranya?", "どうやって"], ["Yang mana?", "どれ・どの"]],
  },
  {
    bab: 17, file: "42", title: "Bentuk -nai", titleJp: "～ない・～なければ なりません",
    hook: "Jangan…, harus…, tidak perlu… Semuanya lahir dari bentuk -nai!",
    cta: "Coba sebutkan hal yang harus dan tidak perlu kamu lakukan besok!",
    patterns: [
      ["Membuat bentuk -nai", "negatif biasa", "v:KKます → v:KKない",
        "I: bunyi sebelum ます → kolom あ + ない (かきます → かかない; ～います → ～わない). II: ます → ない. III: しない, こない.",
        "のみます → のまない", "nomimasu → nomanai", "minum (bentuk -nai)"],
      ["~naide kudasai", "jangan ...", "v:KKない + p:で + d:ください",
        "Untuk meminta supaya JANGAN melakukan sesuatu: bentuk ない + でください.",
        "ここでしゃしんをとらないでください。", "koko de shashin o toranaide kudasai", "Jangan foto di sini."],
      ["~nakereba narimasen", "harus", "v:KKなければ + v:なりません",
        "Untuk keharusan: ～ない → ～なければ なりません. Ingat: ini BUKAN kalimat negatif!",
        "くすりをのまなければなりません。", "kusuri o nomanakereba narimasen", "Harus minum obat."],
      ["~nakute mo ii desu", "tidak perlu", "v:KKなくても + a:いい + d:です",
        "Untuk \"tidak perlu ...\": ～ない → ～なくても いいです.",
        "あしたこなくてもいいです。", "ashita konakute mo ii desu", "Besok tidak perlu datang."],
      ["Objek jadi topik", "を → は", "KB + p:を → KB + p:は",
        "Kalau objek dijadikan TOPIK, を diganti は dan objeknya ditaruh di depan kalimat.",
        "にもつはここにおかないでください。", "nimotsu wa koko ni okanaide kudasai", "Barangnya jangan ditaruh di sini."],
      ["~made ni", "paling lambat", "n:waktu + p:までに + KK",
        "までに = paling lambat / sebelum (tenggat waktu). Beda dengan まで (terus sampai).",
        "かいぎは5じまでにおわります。", "kaigi wa goji made ni owarimasu", "Rapat selesai sebelum pukul 5."],
    ],
    summary: [["Bentuk -nai", "～ない"], ["Jangan ...", "ないでください"], ["Harus", "なければ"],
      ["Tidak perlu", "なくてもいい"], ["Objek jadi topik", "を → は"], ["Paling lambat", "までに"]],
  },
  {
    bab: 18, file: "43", title: "Bentuk Kamus & Bisa", titleJp: "～ことが できます",
    hook: "Bisa main gitar? Hobinya apa? Yuk belajar bentuk kamus dan ことが できます.",
    cta: "Coba ceritakan hobimu pakai ~koto desu!",
    patterns: [
      ["Membuat bentuk kamus", "bentuk dasar", "v:KKます → v:bentuk_kamus",
        "I: bunyi sebelum ます → kolom う (かきます → かく). II: ます → る (たべる). III: する, くる.",
        "かきます → かく", "kakimasu → kaku", "menulis (bentuk kamus)"],
      ["~koto ga dekimasu", "bisa", "KK g:(kamus) + n:こと + p:が + v:できます",
        "Untuk \"bisa\": kata benda + が できます, atau kata kerja bentuk KAMUS + こと が できます.",
        "カードではらうことができます。", "kaado de harau koto ga dekimasu", "Bisa bayar pakai kartu."],
      ["Shumi wa ~koto desu", "hobi", "n:しゅみ + p:は + KK g:(kamus) + n:こと + d:です",
        "Untuk hobi berupa kegiatan: kata kerja bentuk KAMUS + こと です.",
        "わたしのしゅみはおんがくをきくことです。", "watashi no shumi wa ongaku o kiku koto desu", "Hobi saya mendengarkan musik."],
      ["~mae ni", "sebelum ...", "KK g:(kamus) + n:まえに / KB + p:の + n:まえに",
        "Kata kerja bentuk KAMUS + まえに. Kata benda + の まえに. Jangka waktu langsung + まえに.",
        "にほんへくるまえに、にほんごをべんきょうしました。", "Nihon e kuru mae ni, nihongo o benkyou shimashita", "Sebelum ke Jepang, saya belajar bahasa Jepang."],
      ["Nakanaka", "tidak mudah", "o:なかなか + v:KKません",
        "なかなか + bentuk NEGATIF = \"tidak mudah / sulit ...\".",
        "なかなかブロモさんをみることができません。", "nakanaka Buromo-san o miru koto ga dekimasen", "Sulit sekali bisa melihat Gunung Bromo."],
      ["Zehi", "benar-benar", "o:ぜひ + v:KKたいです",
        "ぜひ dipakai bersama harapan atau permintaan: \"benar-benar / sangat ingin\".",
        "ぜひロンボクへいきたいです。", "zehi Ronbok e ikitai desu", "Saya benar-benar ingin ke Lombok."],
    ],
    summary: [["Bentuk kamus", "～る"], ["Bisa", "ことができます"], ["Hobi", "ことです"],
      ["Sebelum ...", "まえに"], ["Tidak mudah", "なかなか"], ["Benar-benar", "ぜひ"]],
  },
  {
    bab: 19, file: "44", title: "Bentuk -ta & Pernah", titleJp: "～た ことが あります",
    hook: "Pernah ke Jepang? Yuk belajar menceritakan pengalaman pakai bentuk -ta.",
    cta: "Coba ceritakan pengalaman paling seru yang pernah kamu alami!",
    patterns: [
      ["Membuat bentuk -ta", "lampau biasa", "v:KKて → v:KKた",
        "Caranya PERSIS bentuk て, tinggal ganti て → た dan で → だ. かいて → かいた, のんで → のんだ.",
        "のみます → のんだ", "nomimasu → nonda", "minum (bentuk -ta)"],
      ["~ta koto ga arimasu", "pernah", "v:KKた + n:こと + p:が + v:あります",
        "Untuk pengalaman \"pernah ...\": bentuk た + ことが あります.",
        "ロンボクへいったことがあります。", "Ronbok e itta koto ga arimasu", "Pernah pergi ke Lombok."],
      ["~tari ~tari shimasu", "antara lain", "v:KKたり + v:KKたり + v:します",
        "Untuk menyebut beberapa kegiatan sebagai CONTOH (tidak urut, tidak semua): bentuk た + り, diulang, ditutup します.",
        "にちようびはテニスをしたり、えいがをみたりします。", "nichiyoubi wa tenisu o shitari, eiga o mitari shimasu", "Hari Minggu main tenis, nonton film, dll."],
      ["~ku / ~ni narimasu", "menjadi", "a:～く / a:～に / KB p:に + v:なります",
        "なります = menjadi. KS-い → ～く なります. KS-な → ～に なります. KB → に なります.",
        "さむくなります。", "samuku narimasu", "Menjadi dingin."],
    ],
    summary: [["Bentuk -ta", "～た"], ["Pernah", "たことがあります"], ["Antara lain", "～たり"], ["Menjadi", "なります"]],
  },
  {
    bab: 20, file: "45", title: "Bahasa Santai", titleJp: "ふつうけい",
    hook: "Ngobrol sama teman nggak perlu kaku! Yuk belajar bahasa santai (bentuk biasa).",
    cta: "Coba ngobrol santai dengan temanmu pakai bentuk biasa!",
    patterns: [
      ["Halus vs Biasa", "dua gaya bicara", "d:いきます → v:いく",
        "Bentuk HALUS (～ます/です) untuk orang baru & atasan. Bentuk BIASA untuk teman & keluarga. いきます → いく, すきです → すきだ.",
        "あしたジャカルタへいく。", "ashita Jakaruta e iku", "Besok pergi ke Jakarta. (santai)"],
      ["Kapan pakai yang mana?", "lihat lawan bicara", "d:Halus → n:atasan / v:Biasa → n:teman",
        "Halus: ke orang yang belum akrab, lebih tua, atau atasan. Biasa: ke teman akrab, keluarga, atau anak kecil.",
        "げんき？ ／ おげんきですか。", "genki? / ogenki desu ka", "Apa kabar? (teman / atasan)"],
      ["Ciri obrolan santai", "lebih ringkas", "p:か g:✕ / p:を・は・が g:✕ / v:～てる",
        "Saat santai: か dihilangkan (cukup nada naik), partikel sering dilepas, ～ている → ～てる, けど = tapi.",
        "コーヒーのむ？", "koohii nomu?", "Mau minum kopi?"],
    ],
    summary: [["Halus vs biasa", "ます → る"], ["Pilih gaya", "atasan・teman"], ["Obrolan santai", "～てる"]],
  },
  {
    bab: 21, file: "46", title: "Pendapat & Kutipan", titleJp: "～と おもいます・～と いいます",
    hook: "Menurutmu gimana? Yuk belajar menyampaikan pendapat dan mengutip omongan orang.",
    cta: "Coba sampaikan pendapatmu pakai ~to omoimasu!",
    patterns: [
      ["~to omoimasu", "saya kira", "n:Bentuk_Biasa + p:と + v:おもいます",
        "Untuk pendapat atau dugaan: isi pikiran pakai BENTUK BIASA + と おもいます. Negatif: ～ないと おもいます.",
        "あしたあめがふるとおもいます。", "ashita ame ga furu to omoimasu", "Saya kira besok hujan."],
      ["~to iimasu", "berkata", "g:「…」 / n:Bentuk_Biasa + p:と + v:いいます",
        "Untuk kutipan. Langsung: pakai 「 」 apa adanya. Tidak langsung: ubah ke bentuk biasa + と いいます.",
        "ブディさんはあしたやすむといいました。", "Budi-san wa ashita yasumu to iimashita", "Budi bilang besok libur."],
      ["~deshou?", "...kan?", "n:Bentuk_Biasa + d:でしょう？",
        "Untuk minta konfirmasi: \"... kan?\". Nadanya NAIK di akhir.",
        "あしたパーティーへいくでしょう？", "ashita paatii e iku deshou?", "Besok ke pesta, kan?"],
      ["[Tempat] de KB ga arimasu", "diadakan di", "n:tempat + p:で + KB + p:が + v:あります",
        "Untuk acara atau kejadian (pesta, festival, rapat), あります artinya \"diadakan\". Tempatnya pakai で.",
        "ジャカルタでサッカーのしあいがあります。", "Jakaruta de sakkaa no shiai ga arimasu", "Di Jakarta ada pertandingan sepak bola."],
      ["KB demo", "...atau apa gitu", "KB + p:でも + KK",
        "でも untuk menawarkan dengan lembut sambil menyebut satu contoh: \"... atau apa gitu\".",
        "ちょっとビールでものみませんか。", "chotto biiru demo nomimasen ka", "Gimana kalau minum bir atau apa gitu?"],
      ["~nai to", "harus (santai)", "v:KKない + p:と",
        "Singkatan santai dari ～なければ なりません (harus). Sering dipakai dalam obrolan sehari-hari.",
        "もうかえらないと…", "mou kaeranai to…", "Aku harus pulang nih..."],
    ],
    summary: [["Saya kira", "とおもいます"], ["Berkata", "といいます"], ["...kan?", "でしょう？"],
      ["Diadakan di", "で～があります"], ["Atau apa gitu", "でも"], ["Harus (santai)", "ないと"]],
  },
  {
    bab: 22, file: "47", title: "Menjelaskan Benda", titleJp: "ブディさんが つくった ケーキ",
    hook: "\"Kue yang dibuat Budi\" — yuk belajar menjelaskan benda pakai kalimat.",
    cta: "Coba jelaskan benda favoritmu pakai anak kalimat!",
    patterns: [
      ["Anak kalimat + KB", "menjelaskan benda", "n:[Bentuk_Biasa] + KB",
        "Taruh kalimat (BENTUK BIASA) DI DEPAN kata benda untuk menjelaskannya. Subjek di dalamnya pakai が. KS-な → な, KB → の.",
        "これはブディさんがつくったケーキです。", "kore wa Budi-san ga tsukutta keeki desu", "Ini kue yang dibuat Budi."],
      ["KK + jikan", "waktu untuk ...", "KK g:(kamus) + n:じかん + p:が + v:あります",
        "Kata kerja bentuk KAMUS di depan じかん (waktu), やくそく (janji), atau ようじ (urusan): \"waktu untuk ...\".",
        "あさごはんをたべるじかんがありません。", "asagohan o taberu jikan ga arimasen", "Tidak ada waktu untuk sarapan."],
      ["~mashou ka", "gimana kalau ...?", "KK + d:ましょうか",
        "Menawarkan diri untuk melakukan sesuatu, termasuk yang dilakukan bersama.",
        "いまからいきましょうか。", "ima kara ikimashou ka", "Bagaimana kalau kita pergi sekarang?"],
    ],
    summary: [["Menjelaskan benda", "［kalimat］＋KB"], ["Waktu untuk ...", "じかん"], ["Gimana kalau ...", "ましょうか"]],
  },
  {
    bab: 23, file: "48", title: "Ketika & Jika", titleJp: "～とき・～と",
    hook: "Ketika…, kalau… — yuk belajar menyatakan waktu dan akibat yang pasti terjadi.",
    cta: "Coba ceritakan apa yang kamu lakukan ketika libur!",
    patterns: [
      ["~toki", "ketika", "n:Bentuk_Biasa + n:とき g:、～",
        "とき = \"ketika\". Sebelum とき pakai bentuk biasa (KS-な → な, KB → の).",
        "ほんをかりるとき、カードがいります。", "hon o kariru toki, kaado ga irimasu", "Ketika meminjam buku, perlu kartu."],
      ["Kamus toki / Ta toki", "sebelum / sesudah", "KK g:(kamus) + n:とき / v:KKた + n:とき",
        "Bentuk KAMUS + とき = sebelum aksi pokok terjadi. Bentuk た + とき = setelah aksi itu selesai.",
        "メダンへいくとき、かばんをかいました。", "Medan e iku toki, kaban o kaimashita", "Waktu mau ke Medan, saya beli tas."],
      ["~to, ~", "kalau ... pasti", "KK g:(kamus) + p:と g:、～",
        "と = \"kalau ... maka otomatis ...\". Untuk hasil yang PASTI (tekan tombol → keluar).",
        "このボタンをおすと、おつりがでます。", "kono botan o osu to, otsuri ga demasu", "Kalau tombol ini ditekan, kembaliannya keluar."],
      ["KB ga KS", "terasa oleh indra", "KB + p:が + KS",
        "Untuk hal yang ditangkap indra (suara, rasa, warna), subjeknya pakai が.",
        "おとがちいさいです。", "oto ga chiisai desu", "Suaranya kecil."],
      ["[Tempat] o KK", "melewati", "n:tempat + p:を + KK",
        "を juga menandai tempat yang DILEWATI: あるきます (jalan di), わたります (menyeberang), まがります (belok).",
        "こうさてんをみぎへまがります。", "kousaten o migi e magarimasu", "Belok kanan di perempatan."],
    ],
    summary: [["Ketika", "とき"], ["Sebelum / sesudah", "る／た とき"], ["Kalau ... pasti", "と"],
      ["Terasa indra", "が"], ["Melewati", "を"]],
  },
  {
    bab: 24, file: "49", title: "Memberi & Menerima Jasa", titleJp: "くれます・～て あげます",
    hook: "Siapa yang sudah membantumu? Yuk belajar memberi dan menerima kebaikan.",
    cta: "Coba ceritakan kebaikan yang pernah orang lain berikan padamu!",
    patterns: [
      ["Kuremasu", "memberi ke aku", "n:orang + p:は + n:わたし + p:に + KB + p:を + v:くれます",
        "くれます = memberi, khusus saat orang lain memberi ke AKU atau keluargaku. (あげます tidak dipakai untuk \"ke saya\".)",
        "デウィさんはわたしにおかしをくれました。", "Dewi-san wa watashi ni okashi o kuremashita", "Dewi memberi saya kue."],
      ["~te agemasu / kuremasu", "memberi jasa", "v:KKて + v:あげます / v:もらいます / v:くれます",
        "て あげます = aku lakukan UNTUK orang. て もらいます = aku dibantu orang. て くれます = orang melakukan untukku.",
        "アンディさんはわたしをえきまでおくってくれました。", "Andi-san wa watashi o eki made okutte kuremashita", "Andi mengantar saya ke stasiun."],
      ["KB wa KB ga KK", "topik + pelaku", "KB1 + p:は + KB2 + p:が + KK",
        "Topik besar pakai は, pelakunya pakai が: \"anggur ini, Dewi yang memberi\".",
        "このワインはデウィさんがくれました。", "kono wain wa Dewi-san ga kuremashita", "Anggur ini Dewi yang memberi."],
    ],
    summary: [["Memberi ke aku", "くれます"], ["Memberi jasa", "～てあげます"], ["Topik + pelaku", "は～が"]],
  },
  {
    bab: 25, file: "50", title: "Pengandaian", titleJp: "～たら・～ても",
    hook: "Kalau punya banyak uang, mau ngapain? Yuk belajar berandai-andai!",
    cta: "Coba ceritakan apa yang ingin kamu lakukan kalau punya waktu libur!",
    patterns: [
      ["~tara", "kalau / jika", "v:～た + p:ら g:、～",
        "Dari bentuk LAMPAU biasa (た) + ら. Kalimat berikutnya bisa berupa keinginan, ajakan, atau permintaan.",
        "おかねがあったら、りょこうします。", "okane ga attara, ryokou shimasu", "Kalau punya uang, saya jalan-jalan."],
      ["KK-tara", "kalau sudah ...", "v:KKたら g:、～",
        "～たら juga untuk \"setelah X (pasti) terjadi, baru Y\".",
        "10じになったら、でかけましょう。", "juuji ni nattara, dekakemashou", "Kalau sudah jam 10, ayo berangkat."],
      ["~te mo", "walaupun", "v:KKて + p:も g:、～",
        "～ても = \"walaupun\". KK: bentuk て + も. KS-い → ～くても. KS-な/KB → でも.",
        "あめがふっても、せんたくします。", "ame ga futte mo, sentaku shimasu", "Walaupun hujan, saya tetap mencuci."],
      ["Moshi", "seandainya", "o:もし + v:～たら",
        "もし di awal kalimat untuk menegaskan pengandaian, dipakai bersama ～たら.",
        "もしおかねがあったら、りょこうしたいです。", "moshi okane ga attara, ryokou shitai desu", "Seandainya punya uang, saya ingin jalan-jalan."],
      ["Subjek anak kalimat", "pakai が", "KB + p:が + g:～たら / g:～とき / g:～から",
        "Dalam anak kalimat (～から, ～とき, ～たら, ～ても), subjeknya pakai が, BUKAN は.",
        "ともだちがこなかったら、どうしますか。", "tomodachi ga konakattara, dou shimasu ka", "Kalau teman tidak datang, bagaimana?"],
    ],
    summary: [["Kalau", "～たら"], ["Kalau sudah ...", "～たら"], ["Walaupun", "～ても"],
      ["Seandainya", "もし"], ["Subjek anak kalimat", "が"]],
  },
];
