// Minna no Nihongo II, Bab 26–50. Pattern rows: [title, tag, formula, desc, jp, romaji, arti]
module.exports = [
  {
    book: "Minna no Nihongo II",
    bab: 26, file: "26", title: "Menyatakan Alasan", titleJp: "～んです",
    hook: "Lihat teman bawa payung basah? Yuk belajar menanyakan dan memberi alasan.",
    cta: "Coba tanyakan alasan sesuatu ke temanmu pakai ~n desu ka!",
    patterns: [
      ["~n desu ka", "menanyakan alasan", "n:Bentuk_Biasa + o:んですか",
        "Dipakai kalau kita lihat/dengar sesuatu lalu penasaran dan minta penjelasan. Kalimatnya diubah ke Bentuk Biasa dulu, baru tempel んですか. Untuk KB & KS-な, だ berubah jadi な.",
        "どうしておくれたんですか。", "doushite okureta n desu ka", "Kenapa terlambat?"],
      ["~n desu", "memberi alasan", "n:Bentuk_Biasa + o:んです",
        "Kalau んですか untuk bertanya, んです untuk MENJAWAB sambil memberi alasan. Jangan dipakai untuk fakta biasa yang bukan alasan.",
        "バスがこなかったんです。", "basu ga konakatta n desu", "Karena busnya tidak datang."],
      ["~n desu ga, ~", "pembuka cerita", "n:Bentuk_Biasa + o:んですが g:、～",
        "が di sini bukan \"tetapi\", hanya kata pembuka yang sopan sebelum minta tolong, mengajak, atau minta izin.",
        "あたまがいたいんですが、かえってもいいですか。", "atama ga itai n desu ga, kaette mo ii desu ka", "Kepala saya sakit, boleh pulang?"],
      ["~te itadakemasen ka", "minta tolong sangat sopan", "v:KKて + o:いただけませんか",
        "Versi paling sopan dari 〜て ください. Kira-kira \"bolehkah saya minta tolong Anda untuk...?\". Cocok untuk orang yang lebih tua, guru, atau atasan.",
        "いいせんせいをしょうかいしていただけませんか。", "ii sensei o shoukai shite itadakemasen ka", "Bisakah Anda mengenalkan saya guru yang baik?"],
      ["Tanya + tara ii desu ka", "minta saran", "t:Kata_Tanya + v:KKたら + d:いいですか",
        "Untuk minta saran: \"sebaiknya saya ... bagaimana/di mana?\". Gabung kata tanya + kata kerja bentuk たら + いいですか.",
        "どこでカメラをかったらいいですか。", "doko de kamera o kattara ii desu ka", "Sebaiknya saya beli kamera di mana?"],
      ["KB (objek) wa ~", "objek jadi topik", "KB g:(objek) + p:は + a:すきです",
        "Kata benda objek dari すきです、きらいです、じょうずです、あります, dll. boleh \"ditarik ke depan\" pakai は untuk menonjolkannya.",
        "カラオケはすきじゃ ないんです。", "karaoke wa suki ja nai n desu", "Kalau karaoke, saya kurang suka."],
    ],
    summary: [["Menanyakan alasan", "んですか"], ["Memberi alasan", "んです"], ["Pembuka cerita", "んですが"],
      ["Minta tolong sopan", "ていただけませんか"], ["Minta saran", "たらいいですか"], ["Objek jadi topik", "は"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 27, file: "27", title: "Bentuk Bisa", titleJp: "可能形",
    hook: "Bisa berbahasa Jepang? Yuk belajar bentuk potensial \"bisa/dapat melakukan\".",
    cta: "Coba sebutkan tiga hal yang bisa kamu lakukan!",
    patterns: [
      ["Membuat bentuk potensial", "bisa melakukan", "v:KKます → n:bentuk_potensial",
        "I: bunyi -u → -e + る (かく→かける). II: る → られる (たべる→たべられる). III: する→できる, くる→こられる. Semuanya lalu berkonjugasi seperti Gol. II.",
        "かんじがよめます。", "kanji ga yomemasu", "(Saya) bisa membaca Kanji."],
      ["Objek o → ga", "kalimat potensial", "KB g:(objek) + p:が + n:KK_Potensial",
        "Kalimat potensial menyatakan KEADAAN (mampu), bukan gerakan. Objek yang biasanya を berubah jadi が. Partikel lain (へ, に) tidak berubah.",
        "アンディさんはにほんごがはなせます。", "Andi-san wa nihongo ga hanasemasu", "Sdr. Andi bisa berbahasa Jepang."],
      ["Miemasu / Kikoemasu", "terlihat / terdengar sendiri", "KB + p:が + v:みえます / v:きこえます",
        "Dipakai saat sesuatu terlihat/terdengar SECARA ALAMI tanpa diusahakan. Kalau butuh niat/usaha, pakai bentuk potensial みられます/きけます.",
        "しんかんせんからふじさんがみえます。", "shinkansen kara Fuji-san ga miemasu", "Dari Shinkansen terlihat Gunung Fuji."],
      ["Dekimasu", "jadi / selesai / terbentuk", "KB + p:が + v:できます",
        "できます di sini bukan \"bisa\", melainkan \"terbentuk, jadi, selesai, dibangun\" — untuk sesuatu yang baru muncul.",
        "えきのまえにスーパーができました。", "eki no mae ni suupaa ga dekimashita", "Di depan stasiun telah dibangun swalayan."],
      ["~shika", "hanya (+ negatif)", "KB + o:しか + v:KKません",
        "しか artinya \"hanya\", WAJIB diikuti bentuk negatif. が/を yang menempel dihilangkan. Beda dengan だけ yang pakai bentuk positif.",
        "ローマじしかかけません。", "roomaji shika kakemasen", "(Saya) hanya bisa menulis huruf latin."],
      ["Wa untuk membandingkan", "kalau A ..., kalau B ...", "n:A + p:は g:… g:、 n:B + p:は g:…",
        "は juga bisa membandingkan dua hal. Kalau menempel pada が/を, partikelnya dilepas; untuk partikel lain は ditempel di belakang (では、には、からは).",
        "ワインはのみますが、ビールはのみません。", "wain wa nomimasu ga, biiru wa nomimasen", "(Saya) minum anggur, tapi tidak minum bir."],
    ],
    summary: [["Bentuk potensial", "～られる"], ["Objek jadi が", "を → が"], ["Terlihat sendiri", "みえます"],
      ["Terbentuk", "できます"], ["Hanya", "しか"], ["Membandingkan", "は"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 28, file: "28", title: "Sambil & Alasan", titleJp: "～ながら・～し",
    hook: "Makan sambil dengar musik? Yuk belajar melakukan dua hal sekaligus dan menumpuk alasan.",
    cta: "Coba ceritakan kegiatan yang biasa kamu lakukan sambil melakukan hal lain!",
    patterns: [
      ["~nagara", "sambil", "v:KK1_akarます + o:ながら + v:KK2",
        "Untuk dua hal sekaligus oleh orang yang sama. Buang ます kata kerja pertama, tempel ながら, lalu sebut kegiatan kedua (aksi utama).",
        "おんがくをききながらしょくじします。", "ongaku o kikinagara shokuji shimasu", "Makan sambil mendengarkan musik."],
      ["~te imasu", "kebiasaan berulang", "v:KKて + d:います",
        "Selain \"sedang\", 〜て います juga menyatakan kebiasaan berulang. Kalau di masa lampau, jadi 〜て いました.",
        "まいあさジョギングをして います。", "maiasa jogingu o shite imasu", "Setiap pagi saya jogging."],
      ["~shi, ~shi", "menyebut beberapa alasan", "n:Bentuk_Biasa + o:し g:、 n:Bentuk_Biasa + o:し",
        "し menumpuk beberapa keterangan/alasan tentang satu topik (\"...begini, ...begitu, lagipula...\"). Sering diikuti それに atau から.",
        "ここはねだんもやすいし、ものもおいしいし……。", "koko wa nedan mo yasui shi, mono mo oishii shi……", "Di sini harganya murah, makanannya enak juga…"],
      ["Sorede", "oleh karena itu", "n:sebab g:。 o:それで g:、 n:akibat",
        "それで menyambungkan dua kalimat: yang depan SEBAB, yang belakang AKIBAT. Mirip \"oleh karena itu / makanya\".",
        "しょうせつかになりたいです。それでいましょうせつをかいて います。", "shousetsuka ni naritai desu. sorede ima shousetsu o kaite imasu", "Saya ingin jadi novelis. Oleh karena itu sekarang saya menulis novel."],
      ["~toki + wa", "pada saat ...", "o:とき + p:は g:…",
        "とき (Bab 23) bisa diberi kata bantu di belakangnya seperti kata benda, misalnya とき+は untuk menonjolkan \"pada saat ...\".",
        "べんきょうするときは、おんがくをききません。", "benkyou suru toki wa, ongaku o kikimasen", "Ketika belajar, saya tidak mendengarkan musik."],
    ],
    summary: [["Sambil", "ながら"], ["Kebiasaan", "ています"], ["Beberapa alasan", "し"],
      ["Oleh karena itu", "それで"], ["Pada saat", "ときは"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 29, file: "29", title: "Keadaan Akibat & Penyesalan", titleJp: "～て しまいました",
    hook: "Dompet jatuh, sayang sekali! Yuk belajar bilang keadaan hasil dan penyesalan.",
    cta: "Coba ceritakan hal yang pernah tidak sengaja kamu lakukan pakai ~te shimaimashita!",
    patterns: [
      ["~te imasu (keadaan)", "keadaan hasil", "v:KK_intransitif_て + d:います",
        "Selain \"sedang\" dan \"kebiasaan\", 〜て います juga menyatakan KEADAAN yang masih berlangsung sebagai hasil kejadian, memakai kata kerja intransitif.",
        "まどガラスがわれて います。", "madogarasu ga warete imasu", "Kaca jendela (dalam keadaan) pecah."],
      ["~te shimaimashita", "sudah tuntas / sayangnya", "v:KKて + o:しまいました",
        "Perbuatan sudah selesai TUNTAS, atau mengungkapkan PENYESALAN (\"sayangnya jadi...\"). Dalam obrolan santai jadi 〜ちゃった.",
        "さいふをおとして しまいました。", "saifu o otoshite shimaimashita", "(Sayangnya) dompet saya terjatuh."],
      ["Tempat ni ikimasu", "へ boleh jadi に", "n:tempat + p:に／へ + v:いきます／きます",
        "Untuk tempat tujuan dengan いきます、きます、かえります, partikel へ boleh diganti に. Keduanya sama benarnya.",
        "こうばんにいかないと。", "kouban ni ikanai to", "Harus pergi ke pos polisi."],
      ["Sore / Sono / Sou", "merujuk hal yang disebut", "t:それ / t:その / t:そう",
        "Kalau これ/それ/あれ (Bab 2) menunjuk benda nyata, それ・その・そう di sini menunjuk HAL yang baru disebut lawan bicara.",
        "さいふをおとしたんです。……それはたいへんですね。", "saifu o otoshitan desu. ……sore wa taihen desu ne", "Dompet saya jatuh. ……Wah, itu repot ya."],
      ["Arimashita", "oh, ketemu!", "g:(setelah mencari) + v:ありました",
        "Bukan berarti \"dulu ada\", tapi ungkapan saat BARU MENEMUKAN sesuatu (\"ah, ini dia!\"), sering diucapkan sambil mencari.",
        "［かばんの なかを みて］……あ、ありました。", "[kaban no naka o mite] …a, arimashita", "[Sambil melihat ke dalam tas] …Ah, ketemu!"],
      ["Dokoka / Dokoka ni", "di / ke suatu tempat", "t:どこか + p:で／に + g:～",
        "どこか menyatakan tempat yang tidak pasti. へ dan を boleh dihilangkan, tapi で dan に TIDAK boleh dihilangkan.",
        "どこかでさいふをなくして しまいました。", "dokoka de saifu o nakushite shimaimashita", "Entah di mana, dompet saya hilang."],
    ],
    summary: [["Keadaan hasil", "ています"], ["Sayangnya", "てしまいました"], ["へ jadi に", "に いきます"],
      ["Merujuk hal itu", "それ・そう"], ["Oh, ketemu!", "ありました"], ["Suatu tempat", "どこか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 30, file: "30", title: "Sengaja Dibuat & Persiapan", titleJp: "～て あります・～て おきます",
    hook: "Catatan sengaja ditulis di meja — yuk belajar bedanya sengaja dan sekadar terjadi.",
    cta: "Coba ceritakan persiapan yang kamu lakukan sebelum bepergian!",
    patterns: [
      ["~te arimasu", "sengaja dibuat, bertahan", "KB + p:が + v:KK_transitif_て + d:あります",
        "Dipakai saat seseorang SENGAJA melakukan sesuatu lalu hasilnya dibiarkan tetap begitu, memakai kata kerja transitif.",
        "つくえのうえにメモがかいて あります。", "tsukue no ue ni memo ga kaite arimasu", "Di atas meja (sudah) ditulis sebuah catatan."],
      ["~te okimasu", "persiapan / membiarkan", "v:KKて + o:おきます",
        "Tiga makna: (1) menyiapkan lebih dulu, (2) mengembalikan ke tempat semula, (3) membiarkan suatu keadaan. Santai: 〜ときます.",
        "りょこうのまえに、きっぷをかって おきます。", "ryokou no mae ni, kippu o katte okimasu", "Sebelum bepergian, membeli karcis dulu."],
      ["Mada + positif", "masih ...", "o:まだ + v:KKて_います g:(positif)",
        "まだ + negatif = \"belum\". まだ + bentuk POSITIF = \"masih\" — keadaan yang sampai sekarang masih berlangsung.",
        "まだあめがふって います。", "mada ame ga futte imasu", "Masih turun hujan."],
      ["~toka ~toka", "menyebut contoh", "KB + o:とか + KB + o:とか",
        "とか mirip や untuk menyebut beberapa CONTOH, tapi bisa ditempel juga di belakang contoh terakhir. Terasa lebih santai.",
        "テニスとかすいえいとか……。", "tenisu toka suiei toka…", "Tenis, renang, dan semacamnya…"],
      ["Partikel + mo", "juga (selain が/を)", "KB + p:に／で／へ + p:も",
        "Kalau も digabung dengan が/を, partikelnya dihapus. Untuk partikel lain (に、で、から、まで), も ditempel di belakangnya.",
        "ほかにもいろいろあります。", "hoka ni mo iroiro arimasu", "Selain ini masih ada macam-macam."],
    ],
    summary: [["Sengaja dibuat", "てあります"], ["Persiapan", "ておきます"], ["Masih", "まだ"],
      ["Contoh", "とか"], ["Partikel + も", "にも・でも"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 31, file: "31", title: "Bentuk Maksud & Rencana", titleJp: "意向形・つもり・予定",
    hook: "Mau ke laut akhir pekan ini? Yuk belajar menyampaikan niat dan rencana.",
    cta: "Coba ceritakan rencanamu akhir pekan ini pakai tsumori desu!",
    patterns: [
      ["Membuat bentuk maksud", "versi santai dari ~mashou", "v:KKます → n:bentuk_maksud",
        "I: -u → -o + う (かく→かこう). II: buang る + よう (たべる→たべよう). III: する→しよう, くる→こよう. Dipakai antar teman akrab.",
        "ちょっとやすまない？……うん、やすもう。", "chotto yasumanai? …un, yasumou", "Istirahat sebentar, yuk? ……Iya, ayo istirahat."],
      ["~ou to omotte imasu", "berniat sejak lama", "n:KK_Bentuk_Maksud + o:と おもって います",
        "Menyampaikan NIAT yang sudah dipikirkan sejak beberapa waktu dan masih dipegang. Bisa juga untuk niat orang ketiga.",
        "しゅうまつうみへいこうと おもって います。", "shuumatsu umi e ikou to omotte imasu", "Akhir pekan ini saya berniat pergi ke laut."],
      ["~tsumori desu", "berniat / tidak berniat", "KK g:(kamus／ない) + o:つもりです",
        "Menyatakan KEHENDAK/tekad yang lebih mantap daripada ようと おもって います. \"Berniat tidak ...\" pakai bentuk ない.",
        "たばこをすわないつもりです。", "tabako o suwanai tsumori desu", "Saya berniat tidak merokok."],
      ["~yotei desu", "rencana / jadwal", "KK g:(kamus)／KB + p:の + o:予定です",
        "予定です untuk RENCANA/jadwal yang sudah ditetapkan (bukan sekadar niat pribadi). Setelah kata benda, sambung dengan の dulu.",
        "りょこうは1しゅうかんぐらいのよていです。", "ryokou wa isshuukan gurai no yotei desu", "Rencananya perjalanan kurang lebih seminggu."],
      ["Mada + te imasen", "belum ...", "o:まだ + v:KKて_いません",
        "Untuk bilang \"belum (terjadi/dikerjakan)\" — sampai saat ini belum terjadi atau belum selesai.",
        "ぎんこうはまだあいて いません。", "ginkou wa mada aite imasen", "Bank belum buka."],
      ["Akar -masu jadi KB", "kepulangan, kesenangan...", "v:KK_akarます → KB",
        "Sebagian kata kerja, kalau ます-nya dibuang, berubah jadi kata benda: かえります→かえり, たのしみます→たのしみ.",
        "かえりにしんかんせんはどこからのりますか。", "kaeri ni shinkansen wa doko kara norimasu ka", "Saat pulang, naik Shinkansen dari mana?"],
    ],
    summary: [["Bentuk maksud", "～よう"], ["Berniat lama", "ようとおもっています"], ["Tekad", "つもり"],
      ["Rencana", "よてい"], ["Belum", "まだ～ていません"], ["KK jadi KB", "akar ます"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 32, file: "32", title: "Nasihat & Kemungkinan", titleJp: "～ほうがいい・でしょう",
    hook: "Sebaiknya olahraga tiap hari! Yuk belajar memberi nasihat dan menduga kemungkinan.",
    cta: "Coba beri satu nasihat ke temanmu pakai ~hou ga ii desu!",
    patterns: [
      ["~hou ga ii desu", "sebaiknya (jangan)", "v:KKた／KKない + o:ほうが いいです",
        "Untuk NASIHAT. \"Sebaiknya dilakukan\" pakai bentuk た; \"sebaiknya jangan\" pakai bentuk ない. Terasa agak memaksa.",
        "まいにちうんどうしたほうが いいです。", "mainichi undou shita hou ga ii desu", "Sebaiknya berolahraga setiap hari."],
      ["Deshou", "mungkin, barangkali", "n:Bentuk_Biasa + o:でしょう",
        "Menyatakan PERKIRAAN tentang hal yang belum pasti, diucapkan dengan nada turun. KB & KS-な: だ dibuang sebelum でしょう.",
        "あしたあめがふるでしょう。", "ashita ame ga furu deshou", "Besok mungkin akan turun hujan."],
      ["Kamo shiremasen", "mungkin saja", "n:Bentuk_Biasa + o:かも しれません",
        "Dipakai kalau ada KEMUNGKINAN walau kecil. Tingkat keyakinannya lebih rendah daripada でしょう. KB & KS-な juga buang だ.",
        "やくそくのじかんにまにあわないかも しれません。", "yakusoku no jikan ni maniawanai kamo shiremasen", "Mungkin saja saya terlambat."],
      ["~mashou (usul)", "mari kita", "v:KK_akarます + d:ましょう",
        "Selain \"ayo\", 〜ましょう juga MENGUSULKAN suatu tindakan dengan tegas. Nuansanya lebih mantap daripada 〜ましょうか.",
        "エンジンのおとがおかしいんです。……ちょっとしらべましょう。", "enjin no oto ga okashiin desu. …chotto shirabemashou", "Bunyi mesinnya aneh. ……Mari kita periksa sebentar."],
      ["Jumlah + de", "batas waktu / biaya", "n:jumlah／waktu + p:で + g:～",
        "で di sini menyatakan BATAS — dalam waktu sekian, atau dengan jumlah/biaya sekian, sesuatu bisa dilakukan.",
        "えきまで30ぷんでいけます。", "eki made 30-pun de ikemasu", "Bisa sampai stasiun dalam 30 menit."],
      ["Nanika + sifat + KB", "sesuatu yang ...", "t:なにか + a:(sifat) + n:こと／もの",
        "Untuk \"sesuatu yang (bersifat) ...\": なにか/どこか dulu, BARU kata sifat + kata benda — bukan sebaliknya.",
        "なにかしんぱいなことがあるんですか。", "nanika shinpai na koto ga arun desu ka", "Apakah ada sesuatu yang mengkhawatirkan?"],
    ],
    summary: [["Sebaiknya", "ほうがいい"], ["Mungkin", "でしょう"], ["Mungkin saja", "かもしれません"],
      ["Mari kita", "ましょう"], ["Batas jumlah", "で"], ["Sesuatu yang", "なにか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 33, file: "33", title: "Perintah, Larangan & Mengutip", titleJp: "命令形・禁止形",
    hook: "\"Semangat!\" \"Dilarang masuk!\" — yuk belajar bentuk perintah dan mengutip tulisan.",
    cta: "Coba cari satu tanda tulisan dan jelaskan artinya pakai to iu imi desu!",
    patterns: [
      ["Bentuk perintah", "keras, jarang dipakai", "v:KKます → n:bentuk_perintah",
        "I: -u → -e (かく→かけ). II: る→ろ (たべる→たべろ). III: する→しろ, くる→こい. Dipakai untuk situasi darurat, aba-aba, atau menyemangati.",
        "がんばれ。", "ganbare", "Semangat!"],
      ["Bentuk larangan", "jangan ...!", "v:KK_Kamus + o:な",
        "Untuk melarang keras, tempel な di belakang Kata Kerja Bentuk Kamus. Versi lebih halus (guru/ortu): KK akar ます + なさい.",
        "はいるな。", "hairu na", "Dilarang masuk!"],
      ["~to kaite arimasu", "tertulis", "g:「…」 + p:と + v:かいて あります",
        "Untuk menyebut apa yang TERTULIS di papan/tanda, atau menanyakan cara baca sebuah Kanji.",
        "あそこに「とまれ」とかいて あります。", "asoko ni \"tomare\" to kaite arimasu", "Di sana tertulis \"Berhenti\"."],
      ["X wa Y to iu imi desu", "X berarti Y", "n:X + p:は + n:Y + o:という + n:意味です",
        "Pola untuk MENJELASKAN ARTI sesuatu. Untuk bertanya arti: どういう 意味ですか (\"apa artinya?\").",
        "「立入禁止」ははいるなという意味です。", "\"tachiiri kinshi\" wa hairu na to iu imi desu", "\"Tachiiri Kinshi\" berarti dilarang masuk."],
      ["~to itte imashita", "katanya ...", "n:Bentuk_Biasa + o:と 言って いました",
        "Untuk MENYAMPAIKAN ULANG perkataan orang ketiga (\"katanya ...\"), berbeda dengan と いいました yang mengutip persis.",
        "デウィさんはあしたやすむと いって いました。", "Dewi-san wa ashita yasumu to itte imashita", "Katanya Sdri. Dewi besok tidak masuk."],
      ["~to tsutaete itadakemasen ka", "tolong sampaikan", "n:Bentuk_Biasa + o:と 伝えて いただけませんか",
        "Pola sopan untuk MENITIP PESAN kepada orang lain (\"tolong sampaikan bahwa ...\"), isinya dibuat Bentuk Biasa dulu.",
        "「あとで でんわ ください」とつたえて いただけませんか。", "\"ato de denwa kudasai\" to tsutaete itadakemasen ka", "Tolong sampaikan: \"Minta ditelepon nanti.\""],
    ],
    summary: [["Bentuk perintah", "命令形"], ["Larangan", "な"], ["Tertulis", "とかいてあります"],
      ["Berarti", "という意味"], ["Katanya", "といっていました"], ["Tolong sampaikan", "とつたえて"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 34, file: "34", title: "Sesuai & Setelah", titleJp: "～とおりに・～あとで",
    hook: "Sesuai contoh, atau setelah selesai? Yuk pelajari urutan dan cara melakukan sesuatu.",
    cta: "Coba ceritakan kegiatanmu setelah pulang kerja/sekolah pakai ~ato de!",
    patterns: [
      ["~toori ni", "sesuai dengan", "v:KKた／KB_の + o:とおりに g:、 KK",
        "とおりに artinya \"sesuai/sama persis dengan\". Setelah kata kerja pakai bentuk た; setelah kata benda pakai の.",
        "わたしがやったとおりに、やって ください。", "watashi ga yatta toori ni, yatte kudasai", "Silakan lakukan sama seperti yang saya buat."],
      ["~ato de", "setelah", "v:KKた／KB_の + o:あとで g:、 KK",
        "Menyatakan urutan waktu: KK2 terjadi SETELAH KK1 selesai. Mirip てから, tapi lebih menekankan urutan waktu saja.",
        "しごとのあとで、のみにいきませんか。", "shigoto no ato de, nomi ni ikimasen ka", "Setelah kerja, mau pergi minum bareng?"],
      ["~te / ~naide", "dengan / tanpa melakukan", "v:KK1て／KK1ないで + KK2",
        "Menyatakan cara/keadaan yang menyertai aksi utama. 〜て = sambil melakukan KK1; 〜ないで = tanpa melakukan KK1.",
        "しょうゆをつけないでたべます。", "shouyu o tsukenaide tabemasu", "Makan tanpa kecap asin."],
    ],
    summary: [["Sesuai", "とおりに"], ["Setelah", "あとで"], ["Dengan / tanpa", "て・ないで"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 35, file: "35", title: "Bentuk Syarat", titleJp: "条件形 ～ば・～なら",
    hook: "Kalau tekan tombol ini, jendela terbuka. Yuk belajar bentuk syarat \"kalau/jika\".",
    cta: "Coba buat satu kalimat pengandaian pakai ~eba!",
    patterns: [
      ["Membuat bentuk syarat", "kalau / jika", "v:KKます → n:bentuk_syarat",
        "I: -u → -e + ば (かく→かけば). II: buang る + れば (たべる→たべれば). III: する→すれば, くる→くれば. KS-い: い→ければ. KS-な/KB: + なら.",
        "ボタンをおせば、まどがあきます。", "botan o oseba, mado ga akimasu", "Kalau menekan tombol, jendela terbuka."],
      ["Bentuk syarat, ~", "kalau / jika", "v:KK_Bentuk_Syarat g:、～ n:(klausa pokok)",
        "Klausa depan = syarat, belakang = hasil. Beda dengan と (otomatis/pasti) dan たら (paling luas). Klausa belakang umumnya tanpa perintah/ajakan.",
        "きっぷがあれば、わたしもいけます。", "kippu ga areba, watashi mo ikemasu", "Kalau ada tiket, saya juga bisa pergi."],
      ["Tanya + eba ii desu ka", "sebaiknya bagaimana?", "t:Kata_Tanya + v:KK_Bentuk_Syarat + d:いいですか",
        "Untuk minta saran/petunjuk, sama maksudnya dengan たら いいですか, tinggal ganti pakai bentuk syarat ば.",
        "どうすればいいですか。", "dou sureba ii desu ka", "Sebaiknya bagaimana caranya?"],
      ["KB nara, ~", "kalau soal ...", "KB + o:なら g:、～",
        "Dipakai untuk menanggapi topik yang dibawa lawan bicara, lalu memberi informasi tentangnya (\"kalau soal ..., maka ...\").",
        "おんせんなら、くさつがいいですよ。", "onsen nara, Kusatsu ga ii desu yo", "Kalau soal onsen, Kusatsu bagus, lho."],
      ["~wa arimasen ka", "pertanyaan halus", "g:～ + p:は + v:ありませんか",
        "Bertanya dengan ありませんか artinya sama dengan ありますか, tapi terasa lebih HALUS karena memberi ruang untuk jawab \"tidak ada\".",
        "どこかいいところはありませんか。", "dokoka ii tokoro wa arimasen ka", "Apakah ada tempat bagus yang bisa direkomendasikan?"],
    ],
    summary: [["Bentuk syarat", "～ば"], ["Kalau / jika", "ば、～"], ["Sebaiknya?", "ばいいですか"],
      ["Kalau soal ...", "なら"], ["Pertanyaan halus", "ありませんか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 36, file: "36", title: "Supaya & Jadi Bisa", titleJp: "～ように・～ように なります",
    hook: "Berlatih tiap hari supaya bisa berenang cepat! Yuk belajar tujuan dan perubahan kemampuan.",
    cta: "Coba ceritakan usaha yang kamu lakukan supaya bisa sesuatu!",
    patterns: [
      ["~you ni, ~", "supaya / agar", "KK g:(kamus／ない) + o:ように g:、 KK2",
        "Menyatakan TUJUAN/harapan. Kata kerja sebelum ように bukan kehendak langsung, melainkan kemampuan/keadaan (termasuk potensial).",
        "はやくおよげるように、まいにちれんしゅうして います。", "hayaku oyogeru you ni, mainichi renshuu shite imasu", "Agar bisa berenang cepat, saya berlatih setiap hari."],
      ["~you ni narimasu", "jadi bisa / berubah", "KK g:(potensial) + o:ように なります",
        "Menyatakan PERUBAHAN keadaan: dari tidak bisa jadi bisa, atau munculnya kebiasaan baru. Negatif: いいえ、まだ 〜ません.",
        "やっとじてんしゃにのれるように なりました。", "yatto jitensha ni noreru you ni narimashita", "Akhirnya saya jadi bisa naik sepeda."],
      ["~you ni shimasu", "berusaha / membiasakan", "KK g:(kamus／ない) + o:ように します",
        "〜ように して います = berusaha sebagai kebiasaan. 〜ように して ください = meminta halus supaya orang berusaha melakukan sesuatu.",
        "まいにちやさいをたべるように して います。", "mainichi yasai o taberu you ni shite imasu", "Saya membiasakan makan sayur setiap hari."],
      ["KS jadi keterangan", "cepat, pandai...", "a:KSい→く / a:KSな→に",
        "Kalau kata sifat menerangkan kata kerja/sifat lain: Sifat-い → い jadi く; Sifat-な → tambah に.",
        "はやくじょうずにおちゃがたてられるように なりたいです。", "hayaku jouzu ni ocha ga taterareru you ni naritai desu", "Saya ingin cepat jadi pandai membuat teh."],
    ],
    summary: [["Supaya", "ように"], ["Jadi bisa", "ようになります"], ["Berusaha", "ようにします"], ["KS jadi keterangan", "く・に"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 37, file: "37", title: "Bentuk Pasif", titleJp: "受身形",
    hook: "Dipuji guru, digigit anjing — yuk belajar bentuk pasif \"di-...\".",
    cta: "Coba ceritakan pengalamanmu pakai bentuk pasif!",
    patterns: [
      ["Membuat bentuk pasif", "di-...", "v:KKます → n:bentuk_pasif",
        "I: -u → -a + れる (かく→かかれる). II: る→られる (ほめる→ほめられる). III: する→される, くる→こられる. Berkonjugasi seperti Gol. II.",
        "ほめます → ほめられます", "homemasu → homeraremasu", "memuji → dipuji"],
      ["A wa B ni + KK pasif", "di-... oleh", "n:A + p:は + n:B + p:に + n:KK_Pasif",
        "Yang DIKENAI perbuatan (A) jadi topik dengan は, pelakunya (B) ditandai に. Pelaku bisa juga bukan manusia.",
        "わたしはせんせいにほめられました。", "watashi wa sensei ni homeraremashita", "Saya dipuji oleh guru."],
      ["Pasif gangguan", "dirugikan", "n:A + p:は + n:B + p:に + KB + p:を + n:KK_Pasif",
        "Dipakai saat barang milik A diapa-apakan B, dan A merasa DIRUGIKAN. Topiknya orangnya, bukan barangnya. Berkesan negatif.",
        "わたしはおとうとにパソコンをこわされました。", "watashi wa otouto ni pasokon o kowasaremashita", "PC saya dirusak oleh adik saya."],
      ["Pasif tanpa fokus pelaku", "diadakan, dibaca", "KB + p:が／は + n:KK_Pasif",
        "Kalau pelakunya tidak penting/umum, benda/peristiwa dijadikan topik dengan pasif. Cocok untuk berita, fakta, sejarah.",
        "おおさかでてんらんかいがひらかれました。", "Oosaka de tenrankai ga hirakaremashita", "Di Osaka diadakan pameran."],
      ["~kara / de tsukuraremasu", "terbuat dari", "KB g:(bahan) + p:から／で + o:つくられます",
        "から kalau bahan bakunya berubah bentuk hingga tak terlihat lagi; で kalau bahannya masih kelihatan.",
        "ビールはむぎからつくられます。", "biiru wa mugi kara tsukuraremasu", "Bir terbuat dari gandum."],
      ["Kono/Sono/Ano + posisi", "letak relatif", "t:あの + n:なか／うえ／した",
        "この・その・あの bisa digabung dengan kata posisi untuk menunjuk letak relatif terhadap benda yang dimaksud.",
        "あのなかにはいれますか。", "ano naka ni hairemasu ka", "Apakah bisa masuk ke dalam (gedung) itu?"],
    ],
    summary: [["Bentuk pasif", "～られる"], ["Di-... oleh", "に + pasif"], ["Dirugikan", "に～を"],
      ["Tanpa pelaku", "が・は"], ["Terbuat dari", "から・で"], ["Posisi relatif", "あの なか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 38, file: "38", title: "Menominakan dengan No", titleJp: "～のは・～のが・～のを",
    hook: "Bermain tenis itu menarik! Yuk belajar mengubah kegiatan jadi seperti kata benda.",
    cta: "Coba sebutkan kegiatan yang menurutmu menarik pakai ~no wa omoshiroi desu!",
    patterns: [
      ["KK kamus no wa + sifat", "melakukan X itu ...", "v:KK_Kamus + o:のは + KS + d:です",
        "の \"menyulap\" kata kerja jadi seperti kata benda. のは + kata sifat menilai SUATU KEGIATAN (\"melakukan ... itu menarik\").",
        "テニスをするのはおもしろいです。", "tenisu o suru no wa omoshiroi desu", "Bermain tenis itu menarik."],
      ["KK kamus no ga + sifat", "suka/pandai melakukan", "v:KK_Kamus + o:のが + KS + d:です",
        "のが + kata sifat dipakai dengan sifat suka/mahir/cepat, dll. (すき、きらい、じょうず、へた、はやい).",
        "はなをそだてるのがすきです。", "hana o sodateru no ga suki desu", "Saya suka memelihara bunga."],
      ["KK kamus no o wasuremashita", "lupa melakukan X", "v:KK_Kamus + o:のを + v:忘れました",
        "Untuk bilang \"lupa MELAKUKAN sesuatu\" (bukan lupa benda), ubah kegiatannya jadi kata benda dengan の lalu tandai を.",
        "ぎゅうにゅうをかうのをわすれました。", "gyuunyuu o kau no o wasuremashita", "Saya lupa membeli susu."],
      ["~no o shitte imasu ka", "tahu bahwa ...?", "n:Bentuk_Biasa + o:のを + v:知って いますか",
        "Untuk menanyakan apakah seseorang TAHU tentang suatu fakta. Isinya diubah ke Bentuk Biasa + の.",
        "ブディさんがけっこんするのをしって いますか。", "Budi-san ga kekkon suru no o shitte imasu ka", "Apakah Anda tahu bahwa Sdr. Budi akan menikah?"],
      ["~no wa KB desu", "yang ... adalah ...", "n:Bentuk_Biasa + o:のは + KB + d:です",
        "Pola penegasan yang menonjolkan satu bagian informasi, sering untuk MENGOREKSI ucapan lawan bicara. Subjek anak kalimat pakai が.",
        "うまれたのはチェンマイです。", "umareta no wa Chenmai desu", "Yang (tempat) lahir saya adalah Chiang Mai."],
    ],
    summary: [["Melakukan X itu ...", "のは"], ["Suka melakukan", "のが"], ["Lupa melakukan", "のを"],
      ["Tahu bahwa", "のを知っています"], ["Yang ... adalah", "のは～です"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 39, file: "39", title: "Menyatakan Sebab", titleJp: "～て・～ので",
    hook: "Kaget dengar berita, kesepian tak bertemu keluarga — yuk belajar sebab dan akibat.",
    cta: "Coba ceritakan sesuatu yang membuatmu kaget atau senang pakai ~te!",
    patterns: [
      ["~te (sebab)", "sebab → akibat (perasaan)", "v:KKて g:、 n:akibat",
        "Bentuk て bisa menyatakan sebab: bagian depan penyebab, belakang akibat (biasanya perasaan di luar kendali). Kalau akibatnya keinginan/perintah, pakai から.",
        "ニュースをきいて、びっくりしました。", "nyuusu o kiite, bikkuri shimashita", "Saya kaget karena mendengar berita itu."],
      ["KB de (sebab)", "bencana / kejadian", "KB g:(bencana) + p:で + g:～",
        "Untuk sebab berupa kejadian/fenomena (gempa, kecelakaan, kebakaran, sakit), cukup pakai kata benda + で.",
        "じしんでビルがたおれました。", "jishin de biru ga taoremashita", "Gedung roboh karena gempa bumi."],
      ["~node, ~", "sebab, lebih halus", "n:Bentuk_Biasa + o:ので g:、～",
        "Sama arti dengan から, tapi lebih halus dan objektif. Cocok untuk meminta izin/pengertian dengan sopan.",
        "にほんごがわからないので、えいごではなして いただけませんか。", "nihongo ga wakaranai node, eigo de hanashite itadakemasen ka", "Karena saya tak paham bahasa Jepang, bisakah berbicara dalam bahasa Inggris?"],
      ["~tochuu de", "di tengah / dalam perjalanan", "KK g:(kamus)／KB_の + o:とちゅうで",
        "Menyatakan \"di tengah-tengah\" suatu kegiatan atau perjalanan. Setelah kata kerja pakai Bentuk Kamus, setelah kata benda pakai の.",
        "マラソンのとちゅうできぶんがわるく なりました。", "marason no tochuu de kibun ga waruku narimashita", "Di tengah maraton, badan jadi kurang enak."],
    ],
    summary: [["Sebab (perasaan)", "て"], ["Sebab (kejadian)", "で"], ["Sebab halus", "ので"], ["Di tengah", "とちゅうで"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 40, file: "40", title: "Pertanyaan dalam Kalimat", titleJp: "～か・～かどうか・～てみます",
    hook: "Coba dulu sebelum yakin! Yuk belajar menyelipkan pertanyaan dan mencoba sesuatu.",
    cta: "Coba tanyakan sesuatu ke temanmu pakai ~ka dou ka!",
    patterns: [
      ["[Bentuk Biasa + tanya] ka, ~", "pertanyaan dalam kalimat", "n:Bentuk_Biasa + t:Kata_Tanya + p:か g:、～",
        "Untuk menyelipkan pertanyaan ber-kata tanya ke dalam kalimat lain, akhiri anak kalimat dengan か. KB & KS-な buang だ.",
        "なんじにとうちゃくするか、しらべて ください。", "nan-ji ni touchaku suru ka, shirabete kudasai", "Tolong cek tiba pukul berapa."],
      ["~ka dou ka, ~", "apakah ... atau tidak", "n:Bentuk_Biasa + o:か どうか g:、～",
        "Untuk menyelipkan pertanyaan ya/tidak tanpa kata tanya. KB & KS-な buang だ.",
        "まちがいがないか どうか、しらべて ください。", "machigai ga nai ka douka, shirabete kudasai", "Tolong periksa apakah ada kesalahan atau tidak."],
      ["~te mimasu", "mencoba melakukan", "v:KKて + o:みます",
        "Melakukan sesuatu untuk DICOBA dulu (\"coba ...\"). 〜て みたい menyampaikan keinginan lebih lembut daripada 〜たい.",
        "このズボンをはいて みてもいいですか。", "kono zubon o haite mite mo ii desu ka", "Bolehkah saya coba pakai celana ini?"],
      ["KS-i → sa", "jadi kata benda", "a:KSい → n:さ",
        "Kata Sifat-い bisa diubah jadi kata benda dengan mengganti い jadi さ: たかい→たかさ, ながい→ながさ.",
        "はしのながさは3,911メートルです。", "hashi no nagasa wa 3,911 meetoru desu", "Panjang jembatan itu 3.911 meter."],
      ["~deshou ka", "pertanyaan sopan", "n:Bentuk_Biasa + o:でしょうか",
        "Membuat pertanyaan jadi lebih lembut & sopan, karena tidak menuntut jawaban pasti. Cocok saat bertanya hati-hati.",
        "アンディさんはがっこうでどうでしょうか。", "Andi-san wa gakkou de dou deshou ka", "Bagaimana keadaan Sdr. Andi di sekolah, ya?"],
    ],
    summary: [["Pertanyaan dalam kalimat", "か、～"], ["Apakah ... atau tidak", "かどうか"], ["Mencoba", "てみます"],
      ["KS jadi KB", "さ"], ["Pertanyaan sopan", "でしょうか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 41, file: "41", title: "Memberi Menerima Sopan", titleJp: "いただきます・くださいます",
    hook: "Menerima oleh-oleh dari atasan? Yuk belajar versi sopan memberi dan menerima.",
    cta: "Coba ceritakan sesuatu yang pernah diberikan orang yang lebih tua kepadamu!",
    patterns: [
      ["Itadakimasu", "menerima dari atasan", "n:atasan + p:に + KB + p:を + o:いただきます",
        "Kalau kita MENERIMA barang dari orang yang lebih tinggi, pakai いただきます (versi sopan dari もらいます). Pemberinya に/から.",
        "わたしはぶちょうにおみやげをいただきました。", "watashi wa buchou ni omiyage o itadakimashita", "Saya menerima oleh-oleh dari kepala bagian."],
      ["Kudasaimasu", "atasan memberi ke kita", "n:atasan + p:が + KB + p:を + o:くださいます",
        "Kalau orang yang lebih tinggi MEMBERI kepada kita, pakai くださいます (versi sopan dari くれます). Pemberinya が.",
        "ぶちょうがおみやげをくださいました。", "buchou ga omiyage o kudasaimashita", "Kepala bagian memberi saya oleh-oleh."],
      ["Yarimasu", "memberi ke yang lebih rendah", "n:adik／hewan + p:に + KB + p:を + o:やります",
        "Untuk MEMBERI ke yang lebih muda/bawahan, hewan, atau tanaman, dulu pakai やります. Sekarang あげます juga umum dipakai.",
        "いぬにえさをやりました。", "inu ni esa o yarimashita", "Saya memberi makan anjing."],
      ["~te itadakimasu/kudasaimasu", "pemberian jasa", "v:KKて + o:いただきます／くださいます／やります",
        "Aturan sopan yang sama berlaku untuk pemberian JASA: いただきます (dibantu atasan), くださいます (atasan membantu kita), やります (kita membantu yang muda).",
        "ぶちょうがえきまでおくって くださいました。", "buchou ga eki made okutte kudasaimashita", "Kepala bagian mengantar saya sampai stasiun."],
      ["~te kudasaimasen ka", "tolong ... (sopan)", "v:KKて + o:くださいませんか",
        "Lebih sopan dari 〜て ください, masih di bawah 〜て いただけませんか. Urutan: ください < くださいませんか < いただけませんか.",
        "つかいかたをおしえて くださいませんか。", "tsukaikata o oshiete kudasaimasen ka", "Tolong ajarkan cara pakainya, ya?"],
      ["KB ni", "sebagai tanda / untuk", "KB + o:に g:(sebagai tanda)",
        "に di sini menandai TUJUAN/maksud sebuah pemberian (\"sebagai tanda ...\", \"untuk oleh-oleh ...\").",
        "けっこんいわいにおさらをくださいました。", "kekkon iwai ni osara o kudasaimashita", "(Beliau) memberi piring sebagai hadiah pernikahan."],
    ],
    summary: [["Menerima (atasan)", "いただきます"], ["Diberi (atasan)", "くださいます"], ["Memberi (bawahan)", "やります"],
      ["Jasa sopan", "ていただきます"], ["Tolong sopan", "くださいませんか"], ["Sebagai tanda", "に"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 42, file: "42", title: "Tujuan & Kegunaan", titleJp: "～ために・～のに",
    hook: "Menabung demi punya toko sendiri! Yuk belajar menyatakan tujuan dan kegunaan.",
    cta: "Coba ceritakan tujuanmu belajar bahasa Jepang pakai ~tame ni!",
    patterns: [
      ["~tame ni, ~", "untuk / demi", "KK g:(kamus)／KB_の + o:ために g:、～",
        "Menyatakan TUJUAN yang ingin dicapai. Kata kerja kehendak (もつ). Beda dengan ように yang pakai kata kerja kemampuan (もてる).",
        "けんこうのために、まいあさはしって います。", "kenkou no tame ni, maiasa hashitte imasu", "Demi kesehatan, saya berlari setiap pagi."],
      ["~no ni tsukaimasu", "kegunaan", "KK g:(kamus)の／KB + p:に + o:つかいます",
        "Untuk menyatakan KEGUNAAN suatu benda (\"dipakai untuk ...\"). Setelah kata kerja, ubah jadi kata benda dengan の lalu tandai に.",
        "このはさみははなをきるのにつかいます。", "kono hasami wa hana o kiru no ni tsukaimasu", "Gunting ini dipakai untuk memotong bunga."],
      ["Jumlah wa / mo", "penekanan jumlah", "n:jumlah + p:は g:(minimal) / p:も g:(banyak)",
        "Jumlah + は = batas MINIMAL (\"setidaknya\"). Jumlah + も = jumlahnya terasa BANYAK (\"sampai ...!\").",
        "はんぶんはちょきんするつもりです。", "hanbun wa chokin suru tsumori desu", "Saya berniat menabung setidaknya separuh."],
      ["~ni yotte + pasif", "oleh (pencipta)", "n:pencipta + o:に よって + n:KK_Pasif",
        "Untuk kata kerja pasif yang menyatakan PENCIPTAAN/PENEMUAN, pelakunya ditandai に よって. Sering di kalimat sejarah.",
        "チキンラーメンはあんどうももふくに よってはつめいされました。", "Chikin Raamen wa Andou Momofuku ni yotte hatsumei saremashita", "Chicken Ramen ditemukan oleh Ando Momofuku."],
    ],
    summary: [["Untuk / demi", "ために"], ["Kegunaan", "のに つかいます"], ["Penekanan jumlah", "は・も"], ["Oleh (pencipta)", "によって"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 43, file: "43", title: "Kelihatannya & Pergi-Kembali", titleJp: "～そうです・～てきます",
    hook: "Kelihatannya mau hujan! Yuk belajar menduga dari penampilan dan urusan singkat.",
    cta: "Coba tebak sesuatu dari penampilannya pakai ~sou desu!",
    patterns: [
      ["~sou desu (penampilan)", "kelihatannya", "v:KK_akarます／KS + o:そうです",
        "Berdasarkan apa yang TERLIHAT. Kata kerja: pertanda akan segera terjadi. Kata sifat: menduga dari penampilan. いい→よさそう, ない→なさそう.",
        "このりょうりはからそうです。", "kono ryouri wa karasou desu", "Masakan ini kelihatannya pedas."],
      ["~te kimasu", "pergi-lakukan-kembali", "v:KKて + o:きます",
        "Menyatakan: pergi ke suatu tempat → melakukan sesuatu → KEMBALI lagi. Cocok untuk urusan singkat.",
        "ちょっとたばこをかって きます。", "chotto tabako o katte kimasu", "Saya pergi beli rokok sebentar (lalu balik)."],
      ["~te kuremasen ka", "tolong ... (akrab)", "v:KKて + o:くれませんか",
        "Lebih halus dari 〜て ください, tapi lebih santai daripada くださいませんか atau いただけませんか. Untuk sederajat/lebih muda.",
        "コンビニでおべんとうをかって きて くれませんか。", "konbini de obentou o katte kite kuremasen ka", "Tolong belikan saya bekal di minimarket, ya?"],
    ],
    summary: [["Kelihatannya", "そうです"], ["Pergi-kembali", "てきます"], ["Tolong (akrab)", "てくれませんか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 44, file: "44", title: "Terlalu, Mudah/Sulit", titleJp: "～すぎます・～やすい",
    hook: "Terlalu banyak minum semalam? Yuk belajar bilang \"terlalu\" dan \"mudah/sulit\".",
    cta: "Coba ceritakan sesuatu yang terlalu banyak/besar/kecil pakai ~sugimasu!",
    patterns: [
      ["~sugimasu", "terlalu ...", "v:KK_akarます／KS + o:すぎます",
        "Menyatakan tingkatan yang KELEWATAN, umumnya berkonotasi kurang baik. いい→よすぎる, ない→なさすぎる.",
        "このセーターはおおきすぎます。", "kono seetaa wa ookisugimasu", "Sweter ini terlalu besar."],
      ["~yasui / ~nikui", "mudah / sulit di-", "v:KK_akarます + o:やすいです／にくいです",
        "やすい = mudah di-...; にくい = sulit di-... Hasilnya berkonjugasi seperti Kata Sifat-い.",
        "このパソコンはつかいやすいです。", "kono pasokon wa tsukaiyasui desu", "PC ini mudah dipakai."],
      ["KS ku/ni shimasu", "mengubah keadaan benda", "a:KSい→く／KSな→に + v:します",
        "Fokus MENGUBAH suatu benda (objek): \"membuat ... jadi (lebih) ...\". Beda dengan なります (berubah sendiri).",
        "へやをきれいにします。", "heya o kirei ni shimasu", "Membersihkan kamar."],
      ["KB ni shimasu", "memutuskan / memilih", "KB + o:に します",
        "Menyatakan PILIHAN atau KEPUTUSAN (\"memutuskan ...\", \"pilih ...\"). Sering saat memesan atau menentukan sesuatu.",
        "へやはシングルに しますか、ツインに しますか。", "heya wa shinguru ni shimasu ka, tsuin ni shimasu ka", "Kamarnya mau pilih single atau twin?"],
    ],
    summary: [["Terlalu", "すぎます"], ["Mudah / sulit", "やすい・にくい"], ["Mengubah benda", "く・にします"], ["Memutuskan", "にします"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 45, file: "45", title: "Dalam Hal & Padahal", titleJp: "～ばあいは・～のに",
    hook: "Padahal sudah janji, kok tidak datang? Yuk belajar mengandaikan kondisi dan kekecewaan.",
    cta: "Coba ceritakan sesuatu yang mengecewakan pakai ~noni!",
    patterns: [
      ["~baai wa, ~", "dalam hal / kalau terjadi", "n:Bentuk_Biasa + o:ばあいは g:、～",
        "Mengandaikan suatu KONDISI, lalu bagian belakang menyebut cara mengatasinya. Sama seperti menerangkan kata benda: KS-な→な, KB→の.",
        "かじのばあいは、エレベーターをつかわないで ください。", "kaji no baai wa, erebeetaa o tsukawanaide kudasai", "Dalam hal kebakaran, jangan gunakan lift."],
      ["~noni, ~", "padahal", "n:Bentuk_Biasa + o:のに g:、～",
        "Dipakai saat kenyataan BERBEDA dari yang diharapkan, mengandung rasa kecewa. Beda dengan が (netral) dan ても (andaian).",
        "やくそくをしたのに、かれはきませんでした。", "yakusoku o shita noni, kare wa kimasen deshita", "Padahal sudah berjanji, dia tidak datang."],
    ],
    summary: [["Dalam hal", "ばあいは"], ["Padahal", "のに"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 46, file: "46", title: "Tahap Kegiatan & Seharusnya", titleJp: "～ところです・～はずです",
    hook: "Baru mau makan, atau sudah selesai? Yuk belajar menyatakan tahap dan keyakinan.",
    cta: "Coba ceritakan apa yang sedang atau baru saja kamu lakukan!",
    patterns: [
      ["~tokoro desu", "akan / sedang / baru saja", "v:KK_Kamus／て_いる／た + o:ところです",
        "KK Kamus + ところ = baru mau. KK て いる + ところ = sedang. KK た + ところ = baru saja selesai.",
        "たったいまバスはでたところです。", "tatta ima basu wa deta tokoro desu", "Busnya baru saja berangkat."],
      ["~bakari desu", "baru saja", "v:KKた + o:ばかりです",
        "Juga berarti \"baru saja\", tapi menekankan PERASAAN pembicara bahwa belum lama berlalu — tak peduli waktu sebenarnya.",
        "せんげつこのかいしゃにはいったばかりです。", "sengetsu kono kaisha ni haitta bakari desu", "Baru saja masuk perusahaan ini bulan lalu."],
      ["~hazu desu", "seharusnya / pasti", "n:Bentuk_Biasa + o:はずです",
        "Menyatakan keyakinan berdasarkan BUKTI/alasan tertentu. Beda dengan でしょう (dugaan) — はず punya dasar yang jelas.",
        "ブディさんはきょうくるはずです。", "Budi-san wa kyou kuru hazu desu", "Sdr. Budi seharusnya datang hari ini."],
    ],
    summary: [["Tahap kegiatan", "ところです"], ["Baru saja (perasaan)", "ばかりです"], ["Seharusnya", "はずです"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 47, file: "47", title: "Katanya & Sepertinya", titleJp: "～そうです・～ようです",
    hook: "Katanya besok dingin, sepertinya ada kecelakaan — yuk beda-bedakan kabar dan kesimpulan.",
    cta: "Coba sampaikan kabar yang kamu dengar pakai ~sou desu!",
    patterns: [
      ["~sou desu (kabar)", "katanya / menurut ~", "n:Bentuk_Biasa + o:そうです",
        "Menyampaikan KABAR dari orang lain apa adanya, tanpa pendapat tambahan. Sumber info: 〜に よると (\"menurut ...\").",
        "バリはとてもきれいだそうです。", "Bari wa totemo kirei da sou desu", "Katanya Bali sangat indah."],
      ["~you desu", "sepertinya / rupanya", "n:Bentuk_Biasa + o:ようです",
        "KESIMPULAN pembicara berdasarkan yang ia amati sendiri, sering didahului どうも. Beda dengan そうです (penampilan luar).",
        "なにかじこのようですね。", "nani ka jiko no you desu ne", "Sepertinya ada kecelakaan."],
      ["Koe/Oto/Nioi/Aji ga shimasu", "terindra", "n:こえ／おと／におい／あじ + p:が + v:します",
        "Untuk sesuatu yang ditangkap panca indra: suara/bunyi terdengar, bau tercium, rasa terasa.",
        "にぎやかなこえがしますね。", "nigiyaka na koe ga shimasu ne", "Terdengar suara ramai, ya."],
    ],
    summary: [["Katanya", "そうです"], ["Sepertinya", "ようです"], ["Terindra", "がします"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 48, file: "48", title: "Bentuk Kausatif", titleJp: "使役形",
    hook: "Menyuruh atau membiarkan? Yuk belajar bentuk kausatif dan mohon izin.",
    cta: "Coba buat kalimat tentang siapa yang menyuruhmu melakukan sesuatu!",
    patterns: [
      ["Membuat bentuk kausatif", "menyuruh / membiarkan", "v:KKます → n:bentuk_kausatif",
        "I: -u → -a + せる (いく→いかせる). II: る→させる (たべる→たべさせる). III: する→させる, くる→こさせる. Berkonjugasi seperti Gol. II.",
        "たべます → たべさせます", "tabemasu → tabesasemasu", "makan → menyuruh/membiarkan makan"],
      ["Orang o + KK kausatif", "kata kerja intransitif", "n:orang + p:を + n:KK_Kausatif",
        "Kalau kata kerjanya INTRANSITIF, orang yang disuruh/dibiarkan ditandai を. Bisa berarti \"memaksa\" atau \"mengizinkan\".",
        "むすめをじゆうにあそばせます。", "musume o jiyuu ni asobasemasu", "(Saya) membiarkan anak perempuan saya bermain bebas."],
      ["Orang ni (benda) o + KK kausatif", "kata kerja transitif", "n:orang + p:に + KB + p:を + n:KK_Kausatif",
        "Kalau kata kerjanya TRANSITIF dan sudah ada objek を, orang yang disuruh ditandai に supaya tidak bentrok.",
        "むすめにあさごはんのじゅんびをてつだわせます。", "musume ni asagohan no junbi o tetsudawasemasu", "(Saya) menyuruh anak perempuan saya membantu menyiapkan sarapan."],
      ["~sasete itadakemasen ka", "mohon izin melakukan", "v:KK_Kausatif_て + o:いただけませんか",
        "Kalau て いただけませんか minta orang lain melakukan, させて いただけませんか minta IZIN agar diri sendiri boleh melakukan.",
        "はやくかえらせて いただけませんか。", "hayaku kaerasete itadakemasen ka", "Mohon izinkan saya pulang lebih cepat."],
    ],
    summary: [["Bentuk kausatif", "～せる"], ["Intransitif + を", "を + kausatif"], ["Transitif + に", "に～を"], ["Mohon izin", "させていただけませんか"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 49, file: "49", title: "Bahasa Hormat", titleJp: "尊敬語",
    hook: "Bapak guru sedang di ruang penelitian — yuk belajar bahasa hormat untuk orang lain.",
    cta: "Coba ubah satu kalimat jadi bahasa hormat pakai ~rare masu!",
    patterns: [
      ["~raremasu (sonkeigo)", "bentuk hormat = pasif", "n:KK_Hormat g:(=bentuk pasif) + o:られます",
        "Keigo untuk menghormati lawan bicara. Bentuk hormat termudah SAMA dengan bentuk pasif: かきます→かかれます.",
        "デウィさんは7じにこられます。", "Dewi-san wa 7-ji ni koraremasu", "Sdri. Dewi akan datang pukul 7."],
      ["O + KK(masu) + ni narimasu", "pola hormat", "o:お + v:KK_akarます + o:に なります",
        "Pola hormat yang lebih halus daripada られます. Tidak dipakai untuk kata kerja bersuku satu (みます、ねます).",
        "しゃちょうはもうおかえりに なりました。", "shachou wa mou okaeri ni narimashita", "Direktur sudah pulang."],
      ["Kata kerja hormat khusus", "irassharu, meshiagaru", "v:いらっしゃる / v:めしあがる / v:なさる",
        "Beberapa kata kerja punya bentuk hormat KHUSUS yang harus dihafal: いらっしゃいます (=いる/いく/くる), めしあがります (=たべる/のむ).",
        "どうぞめしあがって ください。", "douzo meshiagatte kudasai", "Silakan dimakan."],
      ["O/Go + ~ kudasai", "permintaan hormat", "o:お g:(KK) / o:ご g:(KB) + d:ください",
        "Versi hormat dari て ください. KK Gol I/II: お + akar ます + ください; Gol III: ご + kata benda + ください.",
        "どうぞおはいり ください。", "douzo ohairi kudasai", "Silakan masuk."],
      ["O/Go + KB/KS", "awalan hormat", "o:お／ご + KB／KS",
        "Tambahkan お atau ご di depan kata benda/sifat untuk menghormati pemiliknya. お untuk kata asli Jepang, ご untuk serapan Tionghoa.",
        "お名前はなんですか。", "onamae wa nan desu ka", "Siapa nama Anda? (sopan)"],
      ["~mashite / ~masu node", "penyopanan kalimat", "v:KK_akarます + o:まして／ますので",
        "Untuk bicara lebih halus, bentuk て kadang diubah jadi まして, dan ので (sebab) versi sopannya jadi ますので.",
        "アンディさんがねつをだしまして、けさは げんきが なかったんです。", "Andi-san ga netsu o dashimashite, kesa wa genki ga nakattan desu", "Sdr. Andi demam, sehingga pagi ini kurang sehat."],
    ],
    summary: [["Hormat = pasif", "られます"], ["Pola hormat", "おにになります"], ["Kata khusus", "いらっしゃる"],
      ["Permintaan hormat", "お～ください"], ["Awalan hormat", "お・ご"], ["Penyopanan", "まして・ますので"]],
  },
  {
    book: "Minna no Nihongo II",
    bab: 50, file: "50", title: "Bahasa Merendah", titleJp: "謙譲語",
    hook: "\"Saya bernama Budi\" secara sopan — yuk belajar merendahkan diri sendiri.",
    cta: "Coba perkenalkan dirimu pakai bahasa merendah moushimasu!",
    patterns: [
      ["O/Go + ~ shimasu", "merendahkan diri", "o:お g:(KK_I/II) / o:ご g:(KK_III) + v:します",
        "Kenjougo merendahkan AKSI DIRI SENDIRI. Pola: Gol I/II → お + akar ます + します; Gol III → ご + kata benda + します.",
        "にもつをおもち しましょうか。", "nimotsu o omochi shimashou ka", "Mari saya bawakan barangnya."],
      ["Kata kerja merendah khusus", "ukagau, itadaku", "v:うかがう / v:おめに かかる / v:いただく",
        "Beberapa kata kerja punya bentuk merendah KHUSUS: うかがいます (=いく/きく/たずねる), いただきます (=もらう/たべる/のむ).",
        "あしたわたしがうかがいます。", "ashita watashi ga ukagaimasu", "Besok saya yang datang (berkunjung)."],
      ["Kenjougo II", "mairimasu, moushimasu", "v:まいります / v:もうします / v:いたします",
        "Untuk menjelaskan perbuatan diri sendiri secara halus: まいります (=いく/くる), もうします (=いう), いたします (=する), おります (=いる).",
        "わたしはブディともうします。", "watashi wa Budi to moushimasu", "Saya bernama Budi (sopan)."],
    ],
    summary: [["Merendah diri", "お～します"], ["Kata khusus I", "うかがう"], ["Kenjougo II", "まいります"]],
  },
];
